var searchData=
[
  ['faidx1_5ft',['faidx1_t',['../structfaidx1__t.html',1,'']]],
  ['faketimer',['FakeTimer',['../structnvbio_1_1_fake_timer.html',1,'nvbio']]],
  ['fasta_5finc_5freader',['FASTA_inc_reader',['../structnvbio_1_1_f_a_s_t_a__inc__reader.html',1,'nvbio']]],
  ['fasta_5freader',['FASTA_reader',['../structnvbio_1_1_f_a_s_t_a__reader.html',1,'nvbio']]],
  ['fastq_5fbuffer',['FASTQ_buffer',['../structnvbio_1_1_f_a_s_t_q__buffer.html',1,'nvbio']]],
  ['fastq_5ffile',['FASTQ_file',['../structnvbio_1_1_f_a_s_t_q__file.html',1,'nvbio']]],
  ['fastq_5fgzfile',['FASTQ_gzfile',['../structnvbio_1_1_f_a_s_t_q__gzfile.html',1,'nvbio']]],
  ['fastq_5freader',['FASTQ_reader',['../structnvbio_1_1_f_a_s_t_q__reader.html',1,'nvbio']]],
  ['field_5ftraits',['Field_traits',['../structnvbio_1_1_field__traits.html',1,'nvbio']]],
  ['field_5ftraits_3c_20int16_20_3e',['Field_traits&lt; int16 &gt;',['../structnvbio_1_1_field__traits_3_01int16_01_4.html',1,'nvbio']]],
  ['field_5ftraits_3c_20int32_20_3e',['Field_traits&lt; int32 &gt;',['../structnvbio_1_1_field__traits_3_01int32_01_4.html',1,'nvbio']]],
  ['field_5ftraits_3c_20int64_20_3e',['Field_traits&lt; int64 &gt;',['../structnvbio_1_1_field__traits_3_01int64_01_4.html',1,'nvbio']]],
  ['field_5ftraits_3c_20int8_20_3e',['Field_traits&lt; int8 &gt;',['../structnvbio_1_1_field__traits_3_01int8_01_4.html',1,'nvbio']]],
  ['filter',['Filter',['../structnvbio_1_1alndiff_1_1_filter.html',1,'nvbio::alndiff']]],
  ['filter_5fresults',['filter_results',['../structnvbio_1_1mem_1_1filter__results.html',1,'nvbio::mem']]],
  ['filter_5fresults',['filter_results',['../structnvbio_1_1qgram_1_1filter__results.html',1,'nvbio::qgram']]],
  ['filter_5fresults',['filter_results',['../structnvbio_1_1fmindex_1_1filter__results.html',1,'nvbio::fmindex']]],
  ['filter_5fresults_3c_20qgram_5findex_5ftype_2c_20index_5fiterator_2c_20uint2_20_3e',['filter_results&lt; qgram_index_type, index_iterator, uint2 &gt;',['../structnvbio_1_1qgram_1_1filter__results_3_01qgram__index__type_00_01index__iterator_00_01uint2_01_4.html',1,'nvbio::qgram']]],
  ['filter_5fresults_3c_20qgram_5findex_5ftype_2c_20index_5fiterator_2c_20uint32_20_3e',['filter_results&lt; qgram_index_type, index_iterator, uint32 &gt;',['../structnvbio_1_1qgram_1_1filter__results_3_01qgram__index__type_00_01index__iterator_00_01uint32_01_4.html',1,'nvbio::qgram']]],
  ['find_5fk_5fbest_5fpaths_5ffunctor',['find_k_best_paths_functor',['../structfind__k__best__paths__functor.html',1,'']]],
  ['find_5fmax_5fkmer_5foverlaps',['find_max_kmer_overlaps',['../structfind__max__kmer__overlaps.html',1,'']]],
  ['flags',['Flags',['../structnvbio_1_1bowtie2_1_1cuda_1_1_seed_hit_1_1_flags.html',1,'nvbio::bowtie2::cuda::SeedHit']]],
  ['flip_5fedges',['flip_edges',['../structflip__edges.html',1,'']]],
  ['fm_5findex',['fm_index',['../structnvbio_1_1fm__index.html',1,'nvbio']]],
  ['fm_5findex_5fdevice_5fdata',['fm_index_device_data',['../structnvbio_1_1fm__index__device__data.html',1,'nvbio']]],
  ['fmindexdata',['FMIndexData',['../structnvbio_1_1io_1_1_f_m_index_data.html',1,'nvbio::io']]],
  ['fmindexdatacore',['FMIndexDataCore',['../structnvbio_1_1io_1_1_f_m_index_data_core.html',1,'nvbio::io']]],
  ['fmindexdatadevice',['FMIndexDataDevice',['../structnvbio_1_1io_1_1_f_m_index_data_device.html',1,'nvbio::io']]],
  ['fmindexdatahost',['FMIndexDataHost',['../structnvbio_1_1io_1_1_f_m_index_data_host.html',1,'nvbio::io']]],
  ['fmindexdatammap',['FMIndexDataMMAP',['../structnvbio_1_1io_1_1_f_m_index_data_m_m_a_p.html',1,'nvbio::io']]],
  ['fmindexdatammapinfo',['FMIndexDataMMAPInfo',['../structnvbio_1_1io_1_1_f_m_index_data_m_m_a_p_info.html',1,'nvbio::io']]],
  ['fmindexdatammapserver',['FMIndexDataMMAPServer',['../structnvbio_1_1io_1_1_f_m_index_data_m_m_a_p_server.html',1,'nvbio::io']]],
  ['fmindexdef',['FMIndexDef',['../structnvbio_1_1bowtie2_1_1cuda_1_1_f_m_index_def.html',1,'nvbio::bowtie2::cuda']]],
  ['fmindexfilter',['FMIndexFilter',['../structnvbio_1_1_f_m_index_filter.html',1,'nvbio']]],
  ['fmindexfilter_3c_20device_5ftag_2c_20fm_5findex_5ftype_20_3e',['FMIndexFilter&lt; device_tag, fm_index_type &gt;',['../structnvbio_1_1_f_m_index_filter_3_01device__tag_00_01fm__index__type_01_4.html',1,'nvbio']]],
  ['fmindexfilter_3c_20host_5ftag_2c_20fm_5findex_5ftype_20_3e',['FMIndexFilter&lt; host_tag, fm_index_type &gt;',['../structnvbio_1_1_f_m_index_filter_3_01host__tag_00_01fm__index__type_01_4.html',1,'nvbio']]],
  ['fmindexfilterdevice',['FMIndexFilterDevice',['../structnvbio_1_1_f_m_index_filter_device.html',1,'nvbio']]],
  ['fmindexfilterhost',['FMIndexFilterHost',['../structnvbio_1_1_f_m_index_filter_host.html',1,'nvbio']]],
  ['fmt_5faux_5ft',['fmt_aux_t',['../structfmt__aux__t.html',1,'']]],
  ['formatopmarkarray',['FormatOpMarkArray',['../structmgpu_1_1_format_op_mark_array.html',1,'mgpu']]],
  ['formatopmaskbit',['FormatOpMaskBit',['../structmgpu_1_1_format_op_mask_bit.html',1,'mgpu']]],
  ['formatopprintf',['FormatOpPrintf',['../structmgpu_1_1_format_op_printf.html',1,'mgpu']]],
  ['forward_5fpacker',['forward_packer',['../structnvbio_1_1forward__packer.html',1,'nvbio']]],
  ['forward_5fpacker_3c_20big_5fendian_2c_20symbol_5fsize_2c_20symbol_2c_20inputstream_2c_20indextype_2c_20uint4_20_3e',['forward_packer&lt; BIG_ENDIAN, SYMBOL_SIZE, Symbol, InputStream, IndexType, uint4 &gt;',['../structnvbio_1_1forward__packer_3_01_b_i_g___e_n_d_i_a_n_00_01_s_y_m_b_o_l___s_i_z_e_00_01_symbol3da5cf6eab383b28054647b91d5aea50.html',1,'nvbio']]],
  ['forwardpackedstream',['ForwardPackedStream',['../structnvbio_1_1_forward_packed_stream.html',1,'nvbio']]],
  ['from_5fchar_5ffunctor',['from_char_functor',['../structnvbio_1_1from__char__functor.html',1,'nvbio']]]
];
