var searchData=
[
  ['cache_5foverflow',['cache_overflow',['../structnvbio_1_1cache__overflow.html',1,'nvbio']]],
  ['cached_5fiterator',['cached_iterator',['../structnvbio_1_1cached__iterator.html',1,'nvbio']]],
  ['cachedpackedconcatstringset',['CachedPackedConcatStringSet',['../structnvbio_1_1_cached_packed_concat_string_set.html',1,'nvbio']]],
  ['cachedpackedconcatstringset_3c_20streamiterator_2c_20symboltype_2c_20symbol_5fsize_5ft_2c_20big_5fendian_5ft_2c_20lengthiterator_2c_20uint32_20_3e',['CachedPackedConcatStringSet&lt; StreamIterator, SymbolType, SYMBOL_SIZE_T, BIG_ENDIAN_T, LengthIterator, uint32 &gt;',['../structnvbio_1_1_cached_packed_concat_string_set_3_01_stream_iterator_00_01_symbol_type_00_01_s_yafa755ae1af79a3032c5165fea19c2d2.html',1,'nvbio']]],
  ['cachedpackedconcatstringset_3c_20streamiterator_2c_20symboltype_2c_20symbol_5fsize_5ft_2c_20big_5fendian_5ft_2c_20lengthiterator_2c_20uint4_20_3e',['CachedPackedConcatStringSet&lt; StreamIterator, SymbolType, SYMBOL_SIZE_T, BIG_ENDIAN_T, LengthIterator, uint4 &gt;',['../structnvbio_1_1_cached_packed_concat_string_set_3_01_stream_iterator_00_01_symbol_type_00_01_s_y15ce8d7b77036f8cc2a8849c48a26b29.html',1,'nvbio']]],
  ['cachedpackedsparsestringset',['CachedPackedSparseStringSet',['../structnvbio_1_1_cached_packed_sparse_string_set.html',1,'nvbio']]],
  ['cachedpackedsparsestringset_3c_20streamiterator_2c_20symboltype_2c_20symbol_5fsize_5ft_2c_20big_5fendian_5ft_2c_20lengthiterator_2c_20uint32_20_3e',['CachedPackedSparseStringSet&lt; StreamIterator, SymbolType, SYMBOL_SIZE_T, BIG_ENDIAN_T, LengthIterator, uint32 &gt;',['../structnvbio_1_1_cached_packed_sparse_string_set_3_01_stream_iterator_00_01_symbol_type_00_01_s_ycce407d3a9b437130eca2319ae1ca144.html',1,'nvbio']]],
  ['cachedpackedsparsestringset_3c_20streamiterator_2c_20symboltype_2c_20symbol_5fsize_5ft_2c_20big_5fendian_5ft_2c_20lengthiterator_2c_20uint4_20_3e',['CachedPackedSparseStringSet&lt; StreamIterator, SymbolType, SYMBOL_SIZE_T, BIG_ENDIAN_T, LengthIterator, uint4 &gt;',['../structnvbio_1_1_cached_packed_sparse_string_set_3_01_stream_iterator_00_01_symbol_type_00_01_s_y1dafa104033d4da4d00be6a59d61d8de.html',1,'nvbio']]],
  ['cachemanager',['CacheManager',['../struct_cache_manager.html',1,'']]],
  ['cast_5ffunctor',['cast_functor',['../structnvbio_1_1cast__functor.html',1,'nvbio']]],
  ['checkpoint_5fstorage_5ftype',['checkpoint_storage_type',['../structnvbio_1_1aln_1_1checkpoint__storage__type.html',1,'nvbio::aln']]],
  ['checkpoint_5fstorage_5ftype_3c_20editdistancealigner_3c_20type_2c_20algorithm_5ftag_20_3e_20_3e',['checkpoint_storage_type&lt; EditDistanceAligner&lt; TYPE, algorithm_tag &gt; &gt;',['../structnvbio_1_1aln_1_1checkpoint__storage__type_3_01_edit_distance_aligner_3_01_t_y_p_e_00_01algorithm__tag_01_4_01_4.html',1,'nvbio::aln']]],
  ['checkpoint_5fstorage_5ftype_3c_20gotohaligner_3c_20type_2c_20scoring_5ftype_2c_20algorithm_5ftag_20_3e_20_3e',['checkpoint_storage_type&lt; GotohAligner&lt; TYPE, scoring_type, algorithm_tag &gt; &gt;',['../structnvbio_1_1aln_1_1checkpoint__storage__type_3_01_gotoh_aligner_3_01_t_y_p_e_00_01scoring__tycbb0ee894d3d052b0dfd17c9b1dee303.html',1,'nvbio::aln']]],
  ['checkpoint_5fstorage_5ftype_3c_20smithwatermanaligner_3c_20type_2c_20scoring_5ftype_2c_20algorithm_5ftag_20_3e_20_3e',['checkpoint_storage_type&lt; SmithWatermanAligner&lt; TYPE, scoring_type, algorithm_tag &gt; &gt;',['../structnvbio_1_1aln_1_1checkpoint__storage__type_3_01_smith_waterman_aligner_3_01_t_y_p_e_00_01sce06f32b84ad03322f980942861eed557.html',1,'nvbio::aln']]],
  ['chunk',['Chunk',['../struct_bam_tools_1_1_chunk.html',1,'BamTools']]],
  ['chunkloader',['ChunkLoader',['../structnvbio_1_1priv_1_1_chunk_loader.html',1,'nvbio::priv']]],
  ['chunkloader_3c_20symbol_5fsize_2c_20big_5fendian_2c_20storage_5ftype_2c_20offsets_5fiterator_2c_20host_5ftag_2c_20device_5ftag_20_3e',['ChunkLoader&lt; SYMBOL_SIZE, BIG_ENDIAN, storage_type, offsets_iterator, host_tag, device_tag &gt;',['../structnvbio_1_1priv_1_1_chunk_loader_3_01_s_y_m_b_o_l___s_i_z_e_00_01_b_i_g___e_n_d_i_a_n_00_01sd4d1cb938ac0ade718f287ad34236f17.html',1,'nvbio::priv']]],
  ['chunkloader_3c_20symbol_5fsize_2c_20big_5fendian_2c_20storage_5ftype_2c_20offsets_5fiterator_2c_20system_5ftag_2c_20system_5ftag_20_3e',['ChunkLoader&lt; SYMBOL_SIZE, BIG_ENDIAN, storage_type, offsets_iterator, system_tag, system_tag &gt;',['../structnvbio_1_1priv_1_1_chunk_loader_3_01_s_y_m_b_o_l___s_i_z_e_00_01_b_i_g___e_n_d_i_a_n_00_01s389cce8a5c7abaf6aeabeab3d03b07cb.html',1,'nvbio::priv']]],
  ['cigar',['Cigar',['../structnvbio_1_1io_1_1_cigar.html',1,'nvbio::io']]],
  ['cigarop',['CigarOp',['../struct_bam_tools_1_1_cigar_op.html',1,'BamTools']]],
  ['closest_5fdiagonal',['closest_diagonal',['../structnvbio_1_1qgram_1_1closest__diagonal.html',1,'nvbio::qgram']]],
  ['closest_5fdiagonal_3c_20uint2_20_3e',['closest_diagonal&lt; uint2 &gt;',['../structnvbio_1_1qgram_1_1closest__diagonal_3_01uint2_01_4.html',1,'nvbio::qgram']]],
  ['closest_5fdiagonal_3c_20uint4_20_3e',['closest_diagonal&lt; uint4 &gt;',['../structnvbio_1_1qgram_1_1closest__diagonal_3_01uint4_01_4.html',1,'nvbio::qgram']]],
  ['code',['code',['../structcode.html',1,'']]],
  ['collector',['Collector',['../structnvbio_1_1_collector.html',1,'nvbio']]],
  ['column_5fstorage_5ftype',['column_storage_type',['../structnvbio_1_1aln_1_1column__storage__type.html',1,'nvbio::aln']]],
  ['column_5fstorage_5ftype_3c_20editdistancealigner_3c_20type_2c_20algorithm_5ftag_20_3e_20_3e',['column_storage_type&lt; EditDistanceAligner&lt; TYPE, algorithm_tag &gt; &gt;',['../structnvbio_1_1aln_1_1column__storage__type_3_01_edit_distance_aligner_3_01_t_y_p_e_00_01algorithm__tag_01_4_01_4.html',1,'nvbio::aln']]],
  ['column_5fstorage_5ftype_3c_20gotohaligner_3c_20type_2c_20scoring_5ftype_2c_20algorithm_5ftag_20_3e_20_3e',['column_storage_type&lt; GotohAligner&lt; TYPE, scoring_type, algorithm_tag &gt; &gt;',['../structnvbio_1_1aln_1_1column__storage__type_3_01_gotoh_aligner_3_01_t_y_p_e_00_01scoring__type_00_01algorithm__tag_01_4_01_4.html',1,'nvbio::aln']]],
  ['column_5fstorage_5ftype_3c_20smithwatermanaligner_3c_20type_2c_20scoring_5ftype_2c_20algorithm_5ftag_20_3e_20_3e',['column_storage_type&lt; SmithWatermanAligner&lt; TYPE, scoring_type, algorithm_tag &gt; &gt;',['../structnvbio_1_1aln_1_1column__storage__type_3_01_smith_waterman_aligner_3_01_t_y_p_e_00_01scorin66675788ed421ab5227bda03c49e3bbc.html',1,'nvbio::aln']]],
  ['complement_5ffunctor',['complement_functor',['../structnvbio_1_1complement__functor.html',1,'nvbio']]],
  ['component_5ffunctor',['component_functor',['../structnvbio_1_1component__functor.html',1,'nvbio']]],
  ['composition_5ffunctor',['composition_functor',['../structnvbio_1_1composition__functor.html',1,'nvbio']]],
  ['compressionsort',['CompressionSort',['../structnvbio_1_1cuda_1_1_compression_sort.html',1,'nvbio::cuda']]],
  ['concatenated_5fstring_5fset_5ftag',['concatenated_string_set_tag',['../structnvbio_1_1concatenated__string__set__tag.html',1,'nvbio']]],
  ['concatenatedstringset',['ConcatenatedStringSet',['../structnvbio_1_1_concatenated_string_set.html',1,'nvbio']]],
  ['concatenatedstringset_3c_20packedstream_3c_20storage_5ftype_2c_20uint8_2c_20symbol_5fsize_2c_20true_2c_20index_5ftype_20_3e_2c_20offsets_5fiterator_20_3e',['ConcatenatedStringSet&lt; PackedStream&lt; storage_type, uint8, SYMBOL_SIZE, true, index_type &gt;, offsets_iterator &gt;',['../structnvbio_1_1_concatenated_string_set.html',1,'nvbio']]],
  ['condition',['condition',['../structnvbio_1_1cuda_1_1condition.html',1,'nvbio::cuda']]],
  ['condition_5fset_5fstorage',['condition_set_storage',['../structnvbio_1_1cuda_1_1condition__set__storage.html',1,'nvbio::cuda']]],
  ['condition_5fset_5fview',['condition_set_view',['../structnvbio_1_1cuda_1_1condition__set__view.html',1,'nvbio::cuda']]],
  ['config_5fs',['config_s',['../structconfig__s.html',1,'']]],
  ['const_5fcached_5fiterator',['const_cached_iterator',['../structnvbio_1_1const__cached__iterator.html',1,'nvbio']]],
  ['const_5fcast_5fmarker',['const_cast_marker',['../structnvbio_1_1internals_1_1const__cast__marker.html',1,'nvbio::internals']]],
  ['constant',['Constant',['../structnvbio_1_1_constant.html',1,'nvbio']]],
  ['constantcost',['ConstantCost',['../structnvbio_1_1bowtie2_1_1cuda_1_1_constant_cost.html',1,'nvbio::bowtie2::cuda']]],
  ['constantcost_3c_20int_20_3e',['ConstantCost&lt; int &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1_constant_cost.html',1,'nvbio::bowtie2::cuda']]],
  ['context',['Context',['../structnvbio_1_1cuda_1_1_work_queue_3_01_multi_pass_queue_tag_00_01_work_unit_t_00_01_b_l_o_c_k_d_i_m_01_4_1_1_context.html',1,'nvbio::cuda::WorkQueue&lt; MultiPassQueueTag, WorkUnitT, BLOCKDIM &gt;']]],
  ['context',['Context',['../structnvbio_1_1cuda_1_1_work_queue_3_01_ordered_queue_tag_00_01_work_unit_t_00_01_b_l_o_c_k_d_i_m_01_4_1_1_context.html',1,'nvbio::cuda::WorkQueue&lt; OrderedQueueTag, WorkUnitT, BLOCKDIM &gt;']]],
  ['context_5ftype',['context_type',['../structnvbio_1_1aln_1_1priv_1_1_alignment_stream_1_1context__type.html',1,'nvbio::aln::priv::AlignmentStream']]],
  ['context_5ftype',['context_type',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1_alignment_stream_base_1_1context__type.html',1,'nvbio::bowtie2::cuda::detail::AlignmentStreamBase']]],
  ['copy_5fdispatch',['copy_dispatch',['../structnvbio_1_1copy__dispatch.html',1,'nvbio']]],
  ['copy_5finsert_5fpages',['copy_insert_pages',['../structnvbio_1_1copy__insert__pages.html',1,'nvbio']]],
  ['copy_5fmerge_5fpages',['copy_merge_pages',['../structnvbio_1_1copy__merge__pages.html',1,'nvbio']]],
  ['copy_5fpages',['copy_pages',['../structnvbio_1_1copy__pages.html',1,'nvbio']]],
  ['countedbase',['CountedBase',['../classnvbio_1_1internals_1_1_counted_base.html',1,'nvbio::internals']]],
  ['countedbase_3c_20nvbio_3a_3aatomicint32_20_3e',['CountedBase&lt; nvbio::AtomicInt32 &gt;',['../classnvbio_1_1internals_1_1_counted_base.html',1,'nvbio::internals']]],
  ['countedbase_5fimpl',['CountedBase_impl',['../classnvbio_1_1internals_1_1_counted_base__impl.html',1,'nvbio::internals']]],
  ['cpuoutputbatch',['CPUOutputBatch',['../structnvbio_1_1io_1_1_c_p_u_output_batch.html',1,'nvbio::io']]],
  ['ct_5fdata_5fs',['ct_data_s',['../structct__data__s.html',1,'']]],
  ['cuda_5ferror',['cuda_error',['../structnvbio_1_1cuda__error.html',1,'nvbio']]],
  ['cudaalloc',['CudaAlloc',['../classmgpu_1_1_cuda_alloc.html',1,'mgpu']]],
  ['cudaallocbuckets',['CudaAllocBuckets',['../classmgpu_1_1_cuda_alloc_buckets.html',1,'mgpu']]],
  ['cudaallocsimple',['CudaAllocSimple',['../classmgpu_1_1_cuda_alloc_simple.html',1,'mgpu']]],
  ['cudabase',['CudaBase',['../classmgpu_1_1_cuda_base.html',1,'mgpu']]],
  ['cudacontext',['CudaContext',['../classmgpu_1_1_cuda_context.html',1,'mgpu']]],
  ['cudadevice',['CudaDevice',['../classmgpu_1_1_cuda_device.html',1,'mgpu']]],
  ['cudadevicemem',['CudaDeviceMem',['../classmgpu_1_1_cuda_device_mem.html',1,'mgpu']]],
  ['cudaevent',['CudaEvent',['../classmgpu_1_1_cuda_event.html',1,'mgpu']]],
  ['cudaexception',['CudaException',['../classmgpu_1_1_cuda_exception.html',1,'mgpu']]],
  ['cudamemsupport',['CudaMemSupport',['../classmgpu_1_1_cuda_mem_support.html',1,'mgpu']]],
  ['cudatimer',['CudaTimer',['../classmgpu_1_1_cuda_timer.html',1,'mgpu']]]
];
