var searchData=
[
  ['make_5faligner_5fdispatch',['make_aligner_dispatch',['../structnvbio_1_1bowtie2_1_1cuda_1_1make__aligner__dispatch.html',1,'nvbio::bowtie2::cuda']]],
  ['make_5faligner_5fdispatch_3c_20endtoendalignment_2c_20scheme_5ftype_20_3e',['make_aligner_dispatch&lt; EndToEndAlignment, scheme_type &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1make__aligner__dispatch_3_01_end_to_end_alignment_00_01scheme__type_01_4.html',1,'nvbio::bowtie2::cuda']]],
  ['make_5faligner_5fdispatch_3c_20localalignment_2c_20scheme_5ftype_20_3e',['make_aligner_dispatch&lt; LocalAlignment, scheme_type &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1make__aligner__dispatch_3_01_local_alignment_00_01scheme__type_01_4.html',1,'nvbio::bowtie2::cuda']]],
  ['mappedfile',['MappedFile',['../structnvbio_1_1_mapped_file.html',1,'nvbio']]],
  ['mapping_5ferror',['mapping_error',['../structnvbio_1_1_mapped_file_1_1mapping__error.html',1,'nvbio::MappedFile']]],
  ['mapping_5ferror',['mapping_error',['../structnvbio_1_1_server_mapped_file_1_1mapping__error.html',1,'nvbio::ServerMappedFile']]],
  ['mapqfunctorpe',['MapqFunctorPE',['../structnvbio_1_1bowtie2_1_1cuda_1_1_mapq_functor_p_e.html',1,'nvbio::bowtie2::cuda']]],
  ['mapqfunctorse',['MapqFunctorSE',['../structnvbio_1_1bowtie2_1_1cuda_1_1_mapq_functor_s_e.html',1,'nvbio::bowtie2::cuda']]],
  ['mark_5fkmer_5funiqueness',['mark_kmer_uniqueness',['../structmark__kmer__uniqueness.html',1,'']]],
  ['mark_5funique_5fprefix_5fkmer',['mark_unique_prefix_kmer',['../structmark__unique__prefix__kmer.html',1,'']]],
  ['matrixelement',['MatrixElement',['../structmgpu_1_1_matrix_element.html',1,'mgpu']]],
  ['matrixstats',['MatrixStats',['../structmgpu_1_1_matrix_stats.html',1,'mgpu']]],
  ['max_5ffunctor',['max_functor',['../structnvbio_1_1max__functor.html',1,'nvbio']]],
  ['max_5foperator',['max_operator',['../structnvbio_1_1aln_1_1priv_1_1alignment__result_1_1max__operator.html',1,'nvbio::aln::priv::alignment_result']]],
  ['maximum_5fvector_5fwidth',['maximum_vector_width',['../structnvbio_1_1maximum__vector__width.html',1,'nvbio']]],
  ['maximum_5fvector_5fwidth_3c_20char_20_3e',['maximum_vector_width&lt; char &gt;',['../structnvbio_1_1maximum__vector__width_3_01char_01_4.html',1,'nvbio']]],
  ['maximum_5fvector_5fwidth_3c_20int16_20_3e',['maximum_vector_width&lt; int16 &gt;',['../structnvbio_1_1maximum__vector__width_3_01int16_01_4.html',1,'nvbio']]],
  ['maximum_5fvector_5fwidth_3c_20int32_20_3e',['maximum_vector_width&lt; int32 &gt;',['../structnvbio_1_1maximum__vector__width_3_01int32_01_4.html',1,'nvbio']]],
  ['maximum_5fvector_5fwidth_3c_20int64_20_3e',['maximum_vector_width&lt; int64 &gt;',['../structnvbio_1_1maximum__vector__width_3_01int64_01_4.html',1,'nvbio']]],
  ['maximum_5fvector_5fwidth_3c_20int8_20_3e',['maximum_vector_width&lt; int8 &gt;',['../structnvbio_1_1maximum__vector__width_3_01int8_01_4.html',1,'nvbio']]],
  ['maximum_5fvector_5fwidth_3c_20uint16_20_3e',['maximum_vector_width&lt; uint16 &gt;',['../structnvbio_1_1maximum__vector__width_3_01uint16_01_4.html',1,'nvbio']]],
  ['maximum_5fvector_5fwidth_3c_20uint32_20_3e',['maximum_vector_width&lt; uint32 &gt;',['../structnvbio_1_1maximum__vector__width_3_01uint32_01_4.html',1,'nvbio']]],
  ['maximum_5fvector_5fwidth_3c_20uint64_20_3e',['maximum_vector_width&lt; uint64 &gt;',['../structnvbio_1_1maximum__vector__width_3_01uint64_01_4.html',1,'nvbio']]],
  ['maximum_5fvector_5fwidth_3c_20uint8_20_3e',['maximum_vector_width&lt; uint8 &gt;',['../structnvbio_1_1maximum__vector__width_3_01uint8_01_4.html',1,'nvbio']]],
  ['md5_5fctx',['MD5_CTX',['../struct_m_d5___c_t_x.html',1,'']]],
  ['mem_5ffunctor',['mem_functor',['../structnvbio_1_1mem_1_1mem__functor.html',1,'nvbio::mem']]],
  ['mem_5fhandler',['mem_handler',['../structnvbio_1_1mem_1_1mem__handler.html',1,'nvbio::mem']]],
  ['memfilter',['MEMFilter',['../structnvbio_1_1_m_e_m_filter.html',1,'nvbio']]],
  ['memfilter_3c_20device_5ftag_2c_20fm_5findex_5ftype_20_3e',['MEMFilter&lt; device_tag, fm_index_type &gt;',['../structnvbio_1_1_m_e_m_filter_3_01device__tag_00_01fm__index__type_01_4.html',1,'nvbio']]],
  ['memfilter_3c_20host_5ftag_2c_20fm_5findex_5ftype_20_3e',['MEMFilter&lt; host_tag, fm_index_type &gt;',['../structnvbio_1_1_m_e_m_filter_3_01host__tag_00_01fm__index__type_01_4.html',1,'nvbio']]],
  ['memfilterdevice',['MEMFilterDevice',['../structnvbio_1_1_m_e_m_filter_device.html',1,'nvbio']]],
  ['memfilterhost',['MEMFilterHost',['../structnvbio_1_1_m_e_m_filter_host.html',1,'nvbio']]],
  ['memhit',['MEMHit',['../structnvbio_1_1_m_e_m_hit.html',1,'nvbio']]],
  ['mempool_5ft',['mempool_t',['../structmempool__t.html',1,'']]],
  ['memrange',['MEMRange',['../structnvbio_1_1_m_e_m_range.html',1,'nvbio']]],
  ['merge_5fkeys',['merge_keys',['../structnvbio_1_1priv_1_1merge__keys.html',1,'nvbio::priv']]],
  ['mfile',['mFILE',['../structm_f_i_l_e.html',1,'']]],
  ['min_5ffunctor',['min_functor',['../structnvbio_1_1min__functor.html',1,'nvbio']]],
  ['minus_5fone',['minus_one',['../structnvbio_1_1priv_1_1minus__one.html',1,'nvbio::priv']]],
  ['multipassqueuetag',['MultiPassQueueTag',['../structnvbio_1_1cuda_1_1_multi_pass_queue_tag.html',1,'nvbio::cuda']]],
  ['mutex',['Mutex',['../classnvbio_1_1_mutex.html',1,'nvbio']]],
  ['myersbitvectors',['MyersBitVectors',['../structnvbio_1_1aln_1_1priv_1_1_myers_bit_vectors.html',1,'nvbio::aln::priv']]],
  ['myersbitvectors_3c_202_20_3e',['MyersBitVectors&lt; 2 &gt;',['../structnvbio_1_1aln_1_1priv_1_1_myers_bit_vectors_3_012_01_4.html',1,'nvbio::aln::priv']]],
  ['myersbitvectors_3c_204_20_3e',['MyersBitVectors&lt; 4 &gt;',['../structnvbio_1_1aln_1_1priv_1_1_myers_bit_vectors_3_014_01_4.html',1,'nvbio::aln::priv']]],
  ['myersbitvectors_3c_205_20_3e',['MyersBitVectors&lt; 5 &gt;',['../structnvbio_1_1aln_1_1priv_1_1_myers_bit_vectors_3_015_01_4.html',1,'nvbio::aln::priv']]],
  ['myerstag',['MyersTag',['../structnvbio_1_1aln_1_1_myers_tag.html',1,'nvbio::aln']]]
];
