var searchData=
[
  ['sabs',['sAbs',['../structmgpu_1_1s_abs.html',1,'mgpu']]],
  ['same_5ftype',['same_type',['../structnvbio_1_1same__type.html',1,'nvbio']]],
  ['same_5ftype_3c_20t_2c_20t_20_3e',['same_type&lt; T, T &gt;',['../structnvbio_1_1same__type_3_01_t_00_01_t_01_4.html',1,'nvbio']]],
  ['samoutput',['SamOutput',['../structnvbio_1_1io_1_1_sam_output.html',1,'nvbio::io']]],
  ['sbankconflictdivisor',['sBankConflictDivisor',['../structmgpu_1_1s_bank_conflict_divisor.html',1,'mgpu']]],
  ['scan_5fdispatch',['scan_dispatch',['../structnvbio_1_1cuda_1_1scan__dispatch.html',1,'nvbio::cuda']]],
  ['scan_5fdispatch_3c_20t_2c_20op_2c_2016_20_3e',['scan_dispatch&lt; T, Op, 16 &gt;',['../structnvbio_1_1cuda_1_1scan__dispatch_3_01_t_00_01_op_00_0116_01_4.html',1,'nvbio::cuda']]],
  ['scan_5fdispatch_3c_20t_2c_20op_2c_202_20_3e',['scan_dispatch&lt; T, Op, 2 &gt;',['../structnvbio_1_1cuda_1_1scan__dispatch_3_01_t_00_01_op_00_012_01_4.html',1,'nvbio::cuda']]],
  ['scan_5fdispatch_3c_20t_2c_20op_2c_2032_20_3e',['scan_dispatch&lt; T, Op, 32 &gt;',['../structnvbio_1_1cuda_1_1scan__dispatch_3_01_t_00_01_op_00_0132_01_4.html',1,'nvbio::cuda']]],
  ['scan_5fdispatch_3c_20t_2c_20op_2c_204_20_3e',['scan_dispatch&lt; T, Op, 4 &gt;',['../structnvbio_1_1cuda_1_1scan__dispatch_3_01_t_00_01_op_00_014_01_4.html',1,'nvbio::cuda']]],
  ['scan_5fdispatch_3c_20t_2c_20op_2c_208_20_3e',['scan_dispatch&lt; T, Op, 8 &gt;',['../structnvbio_1_1cuda_1_1scan__dispatch_3_01_t_00_01_op_00_018_01_4.html',1,'nvbio::cuda']]],
  ['sconflictfreestorage',['sConflictFreeStorage',['../structmgpu_1_1s_conflict_free_storage.html',1,'mgpu']]],
  ['scopedlock',['ScopedLock',['../classnvbio_1_1_scoped_lock.html',1,'nvbio']]],
  ['scopedtimer',['ScopedTimer',['../structnvbio_1_1_scoped_timer.html',1,'nvbio']]],
  ['scopedtimer',['ScopedTimer',['../structnvbio_1_1cuda_1_1_scoped_timer.html',1,'nvbio::cuda']]],
  ['scorematrices',['ScoreMatrices',['../structnvbio_1_1aln_1_1_score_matrices.html',1,'nvbio::aln']]],
  ['scorematrices_3c_20n_2c_20m_2c_20aln_3a_3aeditdistancetag_20_3e',['ScoreMatrices&lt; N, M, aln::EditDistanceTag &gt;',['../structnvbio_1_1aln_1_1_score_matrices_3_01_n_00_01_m_00_01aln_1_1_edit_distance_tag_01_4.html',1,'nvbio::aln']]],
  ['scorematrices_3c_20n_2c_20m_2c_20aln_3a_3agotohtag_20_3e',['ScoreMatrices&lt; N, M, aln::GotohTag &gt;',['../structnvbio_1_1aln_1_1_score_matrices_3_01_n_00_01_m_00_01aln_1_1_gotoh_tag_01_4.html',1,'nvbio::aln']]],
  ['scorematrices_3c_20n_2c_20m_2c_20aln_3a_3asmithwatermantag_20_3e',['ScoreMatrices&lt; N, M, aln::SmithWatermanTag &gt;',['../structnvbio_1_1aln_1_1_score_matrices_3_01_n_00_01_m_00_01aln_1_1_smith_waterman_tag_01_4.html',1,'nvbio::aln']]],
  ['scorestream',['ScoreStream',['../structnvbio_1_1aln_1_1_score_stream.html',1,'nvbio::aln']]],
  ['scoringqueues',['ScoringQueues',['../structcufmi_1_1bowtie2_1_1cuda_1_1_scoring_queues.html',1,'cufmi::bowtie2::cuda']]],
  ['scoringqueues',['ScoringQueues',['../structnvbio_1_1bowtie2_1_1cuda_1_1_scoring_queues.html',1,'nvbio::bowtie2::cuda']]],
  ['scoringqueuesdeviceview',['ScoringQueuesDeviceView',['../structnvbio_1_1bowtie2_1_1cuda_1_1_scoring_queues_device_view.html',1,'nvbio::bowtie2::cuda']]],
  ['scoringqueuesdeviceview',['ScoringQueuesDeviceView',['../structcufmi_1_1bowtie2_1_1cuda_1_1_scoring_queues_device_view.html',1,'cufmi::bowtie2::cuda']]],
  ['scoringschemeselector',['ScoringSchemeSelector',['../structnvbio_1_1bowtie2_1_1cuda_1_1_scoring_scheme_selector.html',1,'nvbio::bowtie2::cuda']]],
  ['scoringschemeselector_3c_20edit_5fdistance_5fscoring_5ftag_20_3e',['ScoringSchemeSelector&lt; edit_distance_scoring_tag &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1_scoring_scheme_selector_3_01edit__distance__scoring__tag_01_4.html',1,'nvbio::bowtie2::cuda']]],
  ['scoringschemeselector_3c_20smith_5fwaterman_5fscoring_5ftag_20_3e',['ScoringSchemeSelector&lt; smith_waterman_scoring_tag &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1_scoring_scheme_selector_3_01smith__waterman__scoring__tag_01_4.html',1,'nvbio::bowtie2::cuda']]],
  ['scoringschemetag',['ScoringSchemeTag',['../structnvbio_1_1bowtie2_1_1cuda_1_1_scoring_scheme_tag.html',1,'nvbio::bowtie2::cuda']]],
  ['scoringschemetag_3c_20editdistancescoringscheme_20_3e',['ScoringSchemeTag&lt; EditDistanceScoringScheme &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1_scoring_scheme_tag_3_01_edit_distance_scoring_scheme_01_4.html',1,'nvbio::bowtie2::cuda']]],
  ['scoringschemetag_3c_20smithwatermanscoringscheme_3c_20mmcost_2c_20ncost_20_3e_20_3e',['ScoringSchemeTag&lt; SmithWatermanScoringScheme&lt; MMCost, NCost &gt; &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1_scoring_scheme_tag_3_01_smith_waterman_scoring_scheme_3_01_m_m_cost_00_01_n_cost_01_4_01_4.html',1,'nvbio::bowtie2::cuda']]],
  ['sdiv2roundup',['sDiv2RoundUp',['../structmgpu_1_1s_div2_round_up.html',1,'mgpu']]],
  ['sdiv2roundup_3c_20count_2c_200_20_3e',['sDiv2RoundUp&lt; count, 0 &gt;',['../structmgpu_1_1s_div2_round_up_3_01count_00_010_01_4.html',1,'mgpu']]],
  ['sdivsafe',['sDivSafe',['../structmgpu_1_1s_div_safe.html',1,'mgpu']]],
  ['sdivsafe_3c_20x_2c_200_20_3e',['sDivSafe&lt; X, 0 &gt;',['../structmgpu_1_1s_div_safe_3_01_x_00_010_01_4.html',1,'mgpu']]],
  ['sdivup',['sDivUp',['../structmgpu_1_1s_div_up.html',1,'mgpu']]],
  ['seanalyzer',['SEAnalyzer',['../structnvbio_1_1alndiff_1_1_s_e_analyzer.html',1,'nvbio::alndiff']]],
  ['seed_5fmapper',['seed_mapper',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1seed__mapper.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['seed_5fmapper_3c_20approx_5fmapping_20_3e',['seed_mapper&lt; APPROX_MAPPING &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1seed__mapper_3_01_a_p_p_r_o_x___m_a_p_p_i_n_g_01_4.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['seed_5fmapper_3c_20case_5fpruning_5fmapping_20_3e',['seed_mapper&lt; CASE_PRUNING_MAPPING &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1seed__mapper_3_01_c_a_s_e___p_r_u_n_i_n_g___m_a_p_p_i_n_g_01_4.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['seed_5fmapper_3c_20exact_5fmapping_20_3e',['seed_mapper&lt; EXACT_MAPPING &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1seed__mapper_3_01_e_x_a_c_t___m_a_p_p_i_n_g_01_4.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['seedhit',['SeedHit',['../structnvbio_1_1bowtie2_1_1cuda_1_1_seed_hit.html',1,'nvbio::bowtie2::cuda']]],
  ['seedhitdequearray',['SeedHitDequeArray',['../structnvbio_1_1bowtie2_1_1cuda_1_1_seed_hit_deque_array.html',1,'nvbio::bowtie2::cuda']]],
  ['seedhitdequearraydevicestorage',['SeedHitDequeArrayDeviceStorage',['../structnvbio_1_1bowtie2_1_1cuda_1_1_seed_hit_deque_array_device_storage.html',1,'nvbio::bowtie2::cuda']]],
  ['seedhitdequearraydeviceview',['SeedHitDequeArrayDeviceView',['../structnvbio_1_1bowtie2_1_1cuda_1_1_seed_hit_deque_array_device_view.html',1,'nvbio::bowtie2::cuda']]],
  ['seedhitdequearrayhoststorage',['SeedHitDequeArrayHostStorage',['../structnvbio_1_1bowtie2_1_1cuda_1_1_seed_hit_deque_array_host_storage.html',1,'nvbio::bowtie2::cuda']]],
  ['seedhitdequereference',['SeedHitDequeReference',['../structnvbio_1_1bowtie2_1_1cuda_1_1_seed_hit_deque_reference.html',1,'nvbio::bowtie2::cuda']]],
  ['select_5fdispatch',['select_dispatch',['../structnvbio_1_1aln_1_1select__dispatch.html',1,'nvbio::aln']]],
  ['select_5fdispatch_3c_20band_5flen_2c_20simd4u8_20_3e',['select_dispatch&lt; BAND_LEN, simd4u8 &gt;',['../structnvbio_1_1aln_1_1select__dispatch_3_01_b_a_n_d___l_e_n_00_01simd4u8_01_4.html',1,'nvbio::aln']]],
  ['selectbestapproxcontext',['SelectBestApproxContext',['../structnvbio_1_1bowtie2_1_1cuda_1_1_select_best_approx_context.html',1,'nvbio::bowtie2::cuda']]],
  ['sequence_5fstring',['sequence_string',['../structnvbio_1_1io_1_1sequence__string.html',1,'nvbio::io']]],
  ['sequencedata',['SequenceData',['../structnvbio_1_1io_1_1_sequence_data.html',1,'nvbio::io']]],
  ['sequencedataaccess',['SequenceDataAccess',['../structnvbio_1_1io_1_1_sequence_data_access.html',1,'nvbio::io']]],
  ['sequencedataedit',['SequenceDataEdit',['../structnvbio_1_1io_1_1_sequence_data_edit.html',1,'nvbio::io']]],
  ['sequencedataencoder',['SequenceDataEncoder',['../structnvbio_1_1io_1_1_sequence_data_encoder.html',1,'nvbio::io']]],
  ['sequencedataencoderimpl',['SequenceDataEncoderImpl',['../structnvbio_1_1io_1_1_sequence_data_encoder_impl.html',1,'nvbio::io']]],
  ['sequencedatafile',['SequenceDataFile',['../structnvbio_1_1io_1_1_sequence_data_file.html',1,'nvbio::io']]],
  ['sequencedatafile_5fbam',['SequenceDataFile_BAM',['../structnvbio_1_1io_1_1_sequence_data_file___b_a_m.html',1,'nvbio::io']]],
  ['sequencedatafile_5ffasta_5fgz',['SequenceDataFile_FASTA_gz',['../structnvbio_1_1io_1_1_sequence_data_file___f_a_s_t_a__gz.html',1,'nvbio::io']]],
  ['sequencedatafile_5ffastq_5fgz',['SequenceDataFile_FASTQ_gz',['../structnvbio_1_1io_1_1_sequence_data_file___f_a_s_t_q__gz.html',1,'nvbio::io']]],
  ['sequencedatafile_5ffastq_5fparser',['SequenceDataFile_FASTQ_parser',['../structnvbio_1_1io_1_1_sequence_data_file___f_a_s_t_q__parser.html',1,'nvbio::io']]],
  ['sequencedatafile_5fsam',['SequenceDataFile_SAM',['../structnvbio_1_1io_1_1_sequence_data_file___s_a_m.html',1,'nvbio::io']]],
  ['sequencedatafile_5ftxt',['SequenceDataFile_TXT',['../structnvbio_1_1io_1_1_sequence_data_file___t_x_t.html',1,'nvbio::io']]],
  ['sequencedatafile_5ftxt_5fgz',['SequenceDataFile_TXT_gz',['../structnvbio_1_1io_1_1_sequence_data_file___t_x_t__gz.html',1,'nvbio::io']]],
  ['sequencedatainfo',['SequenceDataInfo',['../structnvbio_1_1io_1_1_sequence_data_info.html',1,'nvbio::io']]],
  ['sequencedatammap',['SequenceDataMMAP',['../structnvbio_1_1io_1_1_sequence_data_m_m_a_p.html',1,'nvbio::io']]],
  ['sequencedatammapserver',['SequenceDataMMAPServer',['../structnvbio_1_1io_1_1_sequence_data_m_m_a_p_server.html',1,'nvbio::io']]],
  ['sequencedatastorage',['SequenceDataStorage',['../structnvbio_1_1io_1_1_sequence_data_storage.html',1,'nvbio::io']]],
  ['sequencedatastream',['SequenceDataStream',['../structnvbio_1_1io_1_1_sequence_data_stream.html',1,'nvbio::io']]],
  ['sequencedatatraits',['SequenceDataTraits',['../structnvbio_1_1io_1_1_sequence_data_traits.html',1,'nvbio::io']]],
  ['sequencedataviewcore',['SequenceDataViewCore',['../structnvbio_1_1io_1_1_sequence_data_view_core.html',1,'nvbio::io']]],
  ['sequencestreamloader',['SequenceStreamLoader',['../structnvbio_1_1_sequence_stream_loader.html',1,'nvbio']]],
  ['servermappedfile',['ServerMappedFile',['../structnvbio_1_1_server_mapped_file.html',1,'nvbio']]],
  ['setsuffixflattener',['SetSuffixFlattener',['../structnvbio_1_1priv_1_1_set_suffix_flattener.html',1,'nvbio::priv']]],
  ['sharedcount',['SharedCount',['../classnvbio_1_1internals_1_1_shared_count.html',1,'nvbio::internals']]],
  ['sharedcount_3c_20nvbio_3a_3aatomicint32_20_3e',['SharedCount&lt; nvbio::AtomicInt32 &gt;',['../classnvbio_1_1internals_1_1_shared_count.html',1,'nvbio::internals']]],
  ['sharedpointer',['SharedPointer',['../classnvbio_1_1_shared_pointer.html',1,'nvbio']]],
  ['sharedpointer_3c_20nvbio_3a_3amutex_3a_3aimpl_2c_20nvbio_3a_3aatomicint32_20_3e',['SharedPointer&lt; nvbio::Mutex::Impl, nvbio::AtomicInt32 &gt;',['../classnvbio_1_1_shared_pointer.html',1,'nvbio']]],
  ['sharedpointer_3c_20nvbio_3a_3athreadbase_3a_3aimpl_2c_20nvbio_3a_3aatomicint32_20_3e',['SharedPointer&lt; nvbio::ThreadBase::Impl, nvbio::AtomicInt32 &gt;',['../classnvbio_1_1_shared_pointer.html',1,'nvbio']]],
  ['sharedpointertraits',['SharedPointerTraits',['../structnvbio_1_1internals_1_1_shared_pointer_traits.html',1,'nvbio::internals']]],
  ['sharedpointertraits_3c_20void_20_3e',['SharedPointerTraits&lt; void &gt;',['../structnvbio_1_1internals_1_1_shared_pointer_traits_3_01void_01_4.html',1,'nvbio::internals']]],
  ['sharedpointertraits_3c_20void_20const_20_20_3e',['SharedPointerTraits&lt; void const  &gt;',['../structnvbio_1_1internals_1_1_shared_pointer_traits_3_01void_01const_01_01_4.html',1,'nvbio::internals']]],
  ['sharedpointertraits_3c_20void_20const_20volatile_20_3e',['SharedPointerTraits&lt; void const volatile &gt;',['../structnvbio_1_1internals_1_1_shared_pointer_traits_3_01void_01const_01volatile_01_4.html',1,'nvbio::internals']]],
  ['sharedpointertraits_3c_20void_20volatile_20_3e',['SharedPointerTraits&lt; void volatile &gt;',['../structnvbio_1_1internals_1_1_shared_pointer_traits_3_01void_01volatile_01_4.html',1,'nvbio::internals']]],
  ['shift_5fleft',['shift_left',['../structnvbio_1_1shift__left.html',1,'nvbio']]],
  ['shift_5fright',['shift_right',['../structnvbio_1_1shift__right.html',1,'nvbio']]],
  ['signed_5ftype',['signed_type',['../structnvbio_1_1signed__type.html',1,'nvbio']]],
  ['signed_5ftype_3c_20int32_20_3e',['signed_type&lt; int32 &gt;',['../structnvbio_1_1signed__type_3_01int32_01_4.html',1,'nvbio']]],
  ['signed_5ftype_3c_20int64_20_3e',['signed_type&lt; int64 &gt;',['../structnvbio_1_1signed__type_3_01int64_01_4.html',1,'nvbio']]],
  ['signed_5ftype_3c_20uint32_20_3e',['signed_type&lt; uint32 &gt;',['../structnvbio_1_1signed__type_3_01uint32_01_4.html',1,'nvbio']]],
  ['signed_5ftype_3c_20uint64_20_3e',['signed_type&lt; uint64 &gt;',['../structnvbio_1_1signed__type_3_01uint64_01_4.html',1,'nvbio']]],
  ['simd4u8',['simd4u8',['../structnvbio_1_1simd4u8.html',1,'nvbio']]],
  ['simplefunc',['SimpleFunc',['../structnvbio_1_1bowtie2_1_1cuda_1_1_simple_func.html',1,'nvbio::bowtie2::cuda']]],
  ['simplegotohscheme',['SimpleGotohScheme',['../structnvbio_1_1aln_1_1_simple_gotoh_scheme.html',1,'nvbio::aln']]],
  ['simplesmithwatermanscheme',['SimpleSmithWatermanScheme',['../structnvbio_1_1aln_1_1_simple_smith_waterman_scheme.html',1,'nvbio::aln']]],
  ['sink_5fscore',['sink_score',['../structsink__score.html',1,'']]],
  ['sintegerdiv',['sIntegerDiv',['../structmgpu_1_1s_integer_div.html',1,'mgpu']]],
  ['sispow2',['sIsPow2',['../structmgpu_1_1s_is_pow2.html',1,'mgpu']]],
  ['slogpow2',['sLogPow2',['../structmgpu_1_1s_log_pow2.html',1,'mgpu']]],
  ['slogpow2_3c_200_2c_20roundup_20_3e',['sLogPow2&lt; 0, roundUp &gt;',['../structmgpu_1_1s_log_pow2_3_010_00_01round_up_01_4.html',1,'mgpu']]],
  ['slogpow2_3c_201_2c_20roundup_20_3e',['sLogPow2&lt; 1, roundUp &gt;',['../structmgpu_1_1s_log_pow2_3_011_00_01round_up_01_4.html',1,'mgpu']]],
  ['smax',['sMax',['../structmgpu_1_1s_max.html',1,'mgpu']]],
  ['smin',['sMin',['../structmgpu_1_1s_min.html',1,'mgpu']]],
  ['smith_5fwaterman_5fscoring_5ftag',['smith_waterman_scoring_tag',['../structnvbio_1_1bowtie2_1_1cuda_1_1smith__waterman__scoring__tag.html',1,'nvbio::bowtie2::cuda']]],
  ['smithwatermanaligner',['SmithWatermanAligner',['../structnvbio_1_1aln_1_1_smith_waterman_aligner.html',1,'nvbio::aln']]],
  ['smithwatermancheckpointcontext',['SmithWatermanCheckpointContext',['../structnvbio_1_1aln_1_1priv_1_1banded_1_1_smith_waterman_checkpoint_context.html',1,'nvbio::aln::priv::banded']]],
  ['smithwatermancheckpointedscoringcontext',['SmithWatermanCheckpointedScoringContext',['../structnvbio_1_1aln_1_1priv_1_1banded_1_1_smith_waterman_checkpointed_scoring_context.html',1,'nvbio::aln::priv::banded']]],
  ['smithwatermanscoringcontext',['SmithWatermanScoringContext',['../structnvbio_1_1aln_1_1priv_1_1banded_1_1_smith_waterman_scoring_context.html',1,'nvbio::aln::priv::banded']]],
  ['smithwatermanscoringscheme',['SmithWatermanScoringScheme',['../structnvbio_1_1bowtie2_1_1cuda_1_1_smith_waterman_scoring_scheme.html',1,'nvbio::bowtie2::cuda']]],
  ['smithwatermansubmatrixcontext',['SmithWatermanSubmatrixContext',['../structnvbio_1_1aln_1_1priv_1_1banded_1_1_smith_waterman_submatrix_context.html',1,'nvbio::aln::priv::banded']]],
  ['smithwatermantag',['SmithWatermanTag',['../structnvbio_1_1aln_1_1_smith_waterman_tag.html',1,'nvbio::aln']]],
  ['snp_5fsequence_5findex',['SNP_sequence_index',['../structnvbio_1_1io_1_1_s_n_p__sequence__index.html',1,'nvbio::io']]],
  ['snpdatabase',['SNPDatabase',['../structnvbio_1_1io_1_1_s_n_p_database.html',1,'nvbio::io']]],
  ['snumfactorsof2',['sNumFactorsOf2',['../structmgpu_1_1s_num_factors_of2.html',1,'mgpu']]],
  ['snumfactorsof2_3c_20x_2c_201_20_3e',['sNumFactorsOf2&lt; X, 1 &gt;',['../structmgpu_1_1s_num_factors_of2_3_01_x_00_011_01_4.html',1,'mgpu']]],
  ['sortbuffers',['SortBuffers',['../structnvbio_1_1cuda_1_1_sort_buffers.html',1,'nvbio::cuda']]],
  ['sorteddictionarynode',['SortedDictionaryNode',['../structnvbio_1_1_sorted_dictionary_node.html',1,'nvbio']]],
  ['sorteddictionarysuffixtrie',['SortedDictionarySuffixTrie',['../structnvbio_1_1_sorted_dictionary_suffix_trie.html',1,'nvbio']]],
  ['sortenactor',['SortEnactor',['../structnvbio_1_1cuda_1_1_sort_enactor.html',1,'nvbio::cuda']]],
  ['source_5fdispatch',['source_dispatch',['../structnvbio_1_1copy__dispatch_1_1source__dispatch.html',1,'nvbio::copy_dispatch']]],
  ['sparse_5fstring_5fset_5ftag',['sparse_string_set_tag',['../structnvbio_1_1sparse__string__set__tag.html',1,'nvbio']]],
  ['sparsematrix',['SparseMatrix',['../structmgpu_1_1_sparse_matrix.html',1,'mgpu']]],
  ['sparsestringset',['SparseStringSet',['../structnvbio_1_1_sparse_string_set.html',1,'nvbio']]],
  ['sparsesymbolset',['SparseSymbolSet',['../structnvbio_1_1_sparse_symbol_set.html',1,'nvbio']]],
  ['split_5fmem_5ffunctor',['split_mem_functor',['../structnvbio_1_1mem_1_1split__mem__functor.html',1,'nvbio::mem']]],
  ['srounddown',['sRoundDown',['../structmgpu_1_1s_round_down.html',1,'mgpu']]],
  ['sroundup',['sRoundUp',['../structmgpu_1_1s_round_up.html',1,'mgpu']]],
  ['ssa_5findex_5fmultiple',['SSA_index_multiple',['../structnvbio_1_1_s_s_a__index__multiple.html',1,'nvbio']]],
  ['ssa_5findex_5fmultiple_5fcontext',['SSA_index_multiple_context',['../structnvbio_1_1_s_s_a__index__multiple__context.html',1,'nvbio']]],
  ['ssa_5findex_5fmultiple_5fcontext_3c_20sa_5fint_2c_20const_20uint32_20_2a_20_3e',['SSA_index_multiple_context&lt; SA_INT, const uint32 * &gt;',['../structnvbio_1_1_s_s_a__index__multiple__context.html',1,'nvbio']]],
  ['ssa_5findex_5fmultiple_5fdevice',['SSA_index_multiple_device',['../structnvbio_1_1_s_s_a__index__multiple__device.html',1,'nvbio']]],
  ['ssa_5fvalue_5fmultiple',['SSA_value_multiple',['../structnvbio_1_1_s_s_a__value__multiple.html',1,'nvbio']]],
  ['ssa_5fvalue_5fmultiple_5fcontext',['SSA_value_multiple_context',['../structnvbio_1_1_s_s_a__value__multiple__context.html',1,'nvbio']]],
  ['ssa_5fvalue_5fmultiple_5fdevice',['SSA_value_multiple_device',['../structnvbio_1_1_s_s_a__value__multiple__device.html',1,'nvbio']]],
  ['stackinfo3',['stackinfo3',['../structdivsufsortxx_1_1helper_1_1stackinfo3.html',1,'divsufsortxx::helper']]],
  ['stackinfo4',['stackinfo4',['../structdivsufsortxx_1_1helper_1_1stackinfo4.html',1,'divsufsortxx::helper']]],
  ['stagedalignmentunitbase',['StagedAlignmentUnitBase',['../structnvbio_1_1aln_1_1_staged_alignment_unit_base.html',1,'nvbio::aln']]],
  ['stagedalignmentunitbase_3c_20stream_5ftype_2c_20bandedscoreunit_3c_20band_5flen_2c_20stream_5ftype_20_3e_20_3e',['StagedAlignmentUnitBase&lt; stream_type, BandedScoreUnit&lt; BAND_LEN, stream_type &gt; &gt;',['../structnvbio_1_1aln_1_1_staged_alignment_unit_base.html',1,'nvbio::aln']]],
  ['stagedalignmentunitbase_3c_20stream_5ftype_2c_20stagedscoreunit_3c_20stream_5ftype_20_3e_20_3e',['StagedAlignmentUnitBase&lt; stream_type, StagedScoreUnit&lt; stream_type &gt; &gt;',['../structnvbio_1_1aln_1_1_staged_alignment_unit_base.html',1,'nvbio::aln']]],
  ['stagedscoreunit',['StagedScoreUnit',['../structnvbio_1_1aln_1_1_staged_score_unit.html',1,'nvbio::aln']]],
  ['static_5fcast_5fmarker',['static_cast_marker',['../structnvbio_1_1internals_1_1static__cast__marker.html',1,'nvbio::internals']]],
  ['static_5ftree_5fdesc_5fs',['static_tree_desc_s',['../structstatic__tree__desc__s.html',1,'']]],
  ['stats',['Stats',['../structnvbio_1_1bowtie2_1_1cuda_1_1_stats.html',1,'nvbio::bowtie2::cuda']]],
  ['stats',['Stats',['../structnvbio_1_1alndiff_1_1_stats.html',1,'nvbio::alndiff']]],
  ['stats_3c_20higher_2c_20log_20_3e',['Stats&lt; HIGHER, LOG &gt;',['../structnvbio_1_1alndiff_1_1_stats.html',1,'nvbio::alndiff']]],
  ['stats_3c_20lower_2c_20linear_20_3e',['Stats&lt; LOWER, LINEAR &gt;',['../structnvbio_1_1alndiff_1_1_stats.html',1,'nvbio::alndiff']]],
  ['statspartition',['StatsPartition',['../structnvbio_1_1alndiff_1_1_stats_partition.html',1,'nvbio::alndiff']]],
  ['stream_5ftraits',['stream_traits',['../structnvbio_1_1stream__traits.html',1,'nvbio']]],
  ['stream_5ftraits_3c_20const_20t_20_2a_20_3e',['stream_traits&lt; const T * &gt;',['../structnvbio_1_1stream__traits_3_01const_01_t_01_5_01_4.html',1,'nvbio']]],
  ['stream_5ftraits_3c_20packedstream_3c_20inputstream_2c_20symboltype_2c_20symbol_5fsize_5ft_2c_20big_5fendian_5ft_2c_20indextype_20_3e_20_3e',['stream_traits&lt; PackedStream&lt; InputStream, SymbolType, SYMBOL_SIZE_T, BIG_ENDIAN_T, IndexType &gt; &gt;',['../structnvbio_1_1stream__traits_3_01_packed_stream_3_01_input_stream_00_01_symbol_type_00_01_s_y_mb1bcf1f1d667a89cd075d832bf5de604.html',1,'nvbio']]],
  ['stream_5ftraits_3c_20t_20_2a_20_3e',['stream_traits&lt; T * &gt;',['../structnvbio_1_1stream__traits_3_01_t_01_5_01_4.html',1,'nvbio']]],
  ['streamadapter',['StreamAdapter',['../structnvbio_1_1bowtie2_1_1cuda_1_1_stream_adapter.html',1,'nvbio::bowtie2::cuda']]],
  ['streamadapterbase',['StreamAdapterBase',['../structnvbio_1_1bowtie2_1_1cuda_1_1_stream_adapter_base.html',1,'nvbio::bowtie2::cuda']]],
  ['streamadapterbase_3c_20iterator_2c_20uint32_20_3e',['StreamAdapterBase&lt; Iterator, uint32 &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1_stream_adapter_base_3_01_iterator_00_01uint32_01_4.html',1,'nvbio::bowtie2::cuda']]],
  ['streamadapterbase_3c_20iterator_2c_20uint4_20_3e',['StreamAdapterBase&lt; Iterator, uint4 &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1_stream_adapter_base_3_01_iterator_00_01uint4_01_4.html',1,'nvbio::bowtie2::cuda']]],
  ['strided_5fiterator',['strided_iterator',['../structnvbio_1_1strided__iterator.html',1,'nvbio']]],
  ['strided_5fpacked_5fstring_5fset_5ftag',['strided_packed_string_set_tag',['../structnvbio_1_1strided__packed__string__set__tag.html',1,'nvbio']]],
  ['strided_5fstring_5fset_5ftag',['strided_string_set_tag',['../structnvbio_1_1strided__string__set__tag.html',1,'nvbio']]],
  ['stridedpackedstringset',['StridedPackedStringSet',['../structnvbio_1_1_strided_packed_string_set.html',1,'nvbio']]],
  ['stridedstringset',['StridedStringSet',['../structnvbio_1_1_strided_string_set.html',1,'nvbio']]],
  ['string_5fbwt_5ffunctor',['string_bwt_functor',['../structnvbio_1_1priv_1_1string__bwt__functor.html',1,'nvbio::priv']]],
  ['string_5fqgram_5ffunctor',['string_qgram_functor',['../structnvbio_1_1string__qgram__functor.html',1,'nvbio']]],
  ['string_5fqgram_5fsearch_5ffunctor',['string_qgram_search_functor',['../structnvbio_1_1string__qgram__search__functor.html',1,'nvbio']]],
  ['string_5fseed_5ffunctor',['string_seed_functor',['../structnvbio_1_1string__seed__functor.html',1,'nvbio']]],
  ['string_5fset_5fbwt_5ffunctor',['string_set_bwt_functor',['../structnvbio_1_1priv_1_1string__set__bwt__functor.html',1,'nvbio::priv']]],
  ['string_5fset_5flength_5ffunctor',['string_set_length_functor',['../structnvbio_1_1string__set__length__functor.html',1,'nvbio']]],
  ['string_5fset_5fqgram_5ffunctor',['string_set_qgram_functor',['../structnvbio_1_1string__set__qgram__functor.html',1,'nvbio']]],
  ['string_5fset_5fslice_5ffunctor',['string_set_slice_functor',['../structnvbio_1_1priv_1_1string__set__slice__functor.html',1,'nvbio::priv']]],
  ['string_5fsuffix_5fdifference',['string_suffix_difference',['../structnvbio_1_1priv_1_1string__suffix__difference.html',1,'nvbio::priv']]],
  ['string_5fsuffix_5fless',['string_suffix_less',['../structnvbio_1_1priv_1_1string__suffix__less.html',1,'nvbio::priv']]],
  ['string_5fsuffix_5fword_5ffunctor',['string_suffix_word_functor',['../structnvbio_1_1priv_1_1string__suffix__word__functor.html',1,'nvbio::priv']]],
  ['string_5fsuffix_5fword_5ffunctor_3c_20symbol_5fsize_2c_20word_5fbits_2c_20dollar_5fbits_2c_20packedstream_3c_20storage_5ftype_2c_20symbol_5ftype_2c_20symbol_5fsize_2c_20true_2c_20index_5ftype_20_3e_2c_20word_5ftype_20_3e',['string_suffix_word_functor&lt; SYMBOL_SIZE, WORD_BITS, DOLLAR_BITS, PackedStream&lt; storage_type, symbol_type, SYMBOL_SIZE, true, index_type &gt;, word_type &gt;',['../structnvbio_1_1priv_1_1string__suffix__word__functor_3_01_s_y_m_b_o_l___s_i_z_e_00_01_w_o_r_d___af1d7fb42ac84d721634051864dc80bd.html',1,'nvbio::priv']]],
  ['stringbwthandler',['StringBWTHandler',['../structnvbio_1_1_string_b_w_t_handler.html',1,'nvbio']]],
  ['stringbwthandler_3c_20string_5ftype_2c_20output_5fbwt_5fiterator_20_3e',['StringBWTHandler&lt; string_type, output_bwt_iterator &gt;',['../structnvbio_1_1_string_b_w_t_handler.html',1,'nvbio']]],
  ['stringbwtssahandler',['StringBWTSSAHandler',['../structnvbio_1_1_string_b_w_t_s_s_a_handler.html',1,'nvbio']]],
  ['stringprefetcher',['StringPrefetcher',['../structnvbio_1_1_string_prefetcher.html',1,'nvbio']]],
  ['stringprefetcher_3c_20infix_3c_20packedstream_3c_20storageiterator_2c_20uint8_2c_20symbol_5fsize_5ft_2c_20big_5fendian_5ft_20_3e_2c_20infixcoordtype_20_3e_2c_20lmem_5fcache_5ftag_3c_20cache_5fsize_20_3e_20_3e',['StringPrefetcher&lt; Infix&lt; PackedStream&lt; StorageIterator, uint8, SYMBOL_SIZE_T, BIG_ENDIAN_T &gt;, InfixCoordType &gt;, lmem_cache_tag&lt; CACHE_SIZE &gt; &gt;',['../structnvbio_1_1_string_prefetcher_3_01_infix_3_01_packed_stream_3_01_storage_iterator_00_01uint8e9a31f95d7f572943e276df0b7f0363a.html',1,'nvbio']]],
  ['stringprefetcher_3c_20infix_3c_20vector_5fview_3c_20packedstream_3c_20storageiterator_2c_20uint8_2c_20symbol_5fsize_5ft_2c_20big_5fendian_5ft_20_3e_20_3e_2c_20infixcoordtype_20_3e_2c_20lmem_5fcache_5ftag_3c_20cache_5fsize_20_3e_20_3e',['StringPrefetcher&lt; Infix&lt; vector_view&lt; PackedStream&lt; StorageIterator, uint8, SYMBOL_SIZE_T, BIG_ENDIAN_T &gt; &gt;, InfixCoordType &gt;, lmem_cache_tag&lt; CACHE_SIZE &gt; &gt;',['../structnvbio_1_1_string_prefetcher_3_01_infix_3_01vector__view_3_01_packed_stream_3_01_storage_it90896505d6936a26b3731f6a0dab7be2.html',1,'nvbio']]],
  ['stringprefetcher_3c_20input_5fpattern_5fstring_2c_20lmem_5fcache_5ftag_3c_20128_20_3e_20_3e',['StringPrefetcher&lt; input_pattern_string, lmem_cache_tag&lt; 128 &gt; &gt;',['../structnvbio_1_1_string_prefetcher.html',1,'nvbio']]],
  ['stringprefetcher_3c_20input_5ftext_5fstring_2c_20lmem_5fcache_5ftag_3c_20128_20_3e_20_3e',['StringPrefetcher&lt; input_text_string, lmem_cache_tag&lt; 128 &gt; &gt;',['../structnvbio_1_1_string_prefetcher.html',1,'nvbio']]],
  ['stringprefetcher_3c_20vector_5fview_3c_20packedstream_3c_20storageiterator_2c_20uint8_2c_20symbol_5fsize_5ft_2c_20big_5fendian_5ft_20_3e_20_3e_2c_20lmem_5fcache_5ftag_3c_20cache_5fsize_20_3e_20_3e',['StringPrefetcher&lt; vector_view&lt; PackedStream&lt; StorageIterator, uint8, SYMBOL_SIZE_T, BIG_ENDIAN_T &gt; &gt;, lmem_cache_tag&lt; CACHE_SIZE &gt; &gt;',['../structnvbio_1_1_string_prefetcher_3_01vector__view_3_01_packed_stream_3_01_storage_iterator_00_00f3bb135ec59bb62595265176042b5b0.html',1,'nvbio']]],
  ['strings_5ftype',['strings_type',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1_alignment_stream_base_1_1strings__type.html',1,'nvbio::bowtie2::cuda::detail::AlignmentStreamBase']]],
  ['strings_5ftype',['strings_type',['../structnvbio_1_1aln_1_1priv_1_1_alignment_stream_1_1strings__type.html',1,'nvbio::aln::priv::AlignmentStream']]],
  ['stringsetiterator',['StringSetIterator',['../structnvbio_1_1_string_set_iterator.html',1,'nvbio']]],
  ['stringssahandler',['StringSSAHandler',['../structnvbio_1_1_string_s_s_a_handler.html',1,'nvbio']]],
  ['stringssahandler_3c_20output_5fssa_5fiterator_20_3e',['StringSSAHandler&lt; output_ssa_iterator &gt;',['../structnvbio_1_1_string_s_s_a_handler.html',1,'nvbio']]],
  ['stringsuffixbucketer',['StringSuffixBucketer',['../structnvbio_1_1priv_1_1_string_suffix_bucketer.html',1,'nvbio::priv']]],
  ['substring_5fwrapper',['substring_wrapper',['../classdivsufsortxx_1_1substring_1_1substring__wrapper.html',1,'divsufsortxx::substring']]],
  ['suffix',['Suffix',['../structnvbio_1_1_suffix.html',1,'nvbio']]],
  ['suffix_5fcomponent_5ffunctor',['suffix_component_functor',['../structnvbio_1_1priv_1_1suffix__component__functor.html',1,'nvbio::priv']]],
  ['suffix_5foffset_5ffunctor',['suffix_offset_functor',['../structnvbio_1_1priv_1_1suffix__offset__functor.html',1,'nvbio::priv']]],
  ['suffix_5franker',['suffix_ranker',['../structnvbio_1_1priv_1_1suffix__ranker.html',1,'nvbio::priv']]],
  ['suffix_5franker_3c_202_20_3e',['suffix_ranker&lt; 2 &gt;',['../structnvbio_1_1priv_1_1suffix__ranker_3_012_01_4.html',1,'nvbio::priv']]],
  ['suffixcore',['SuffixCore',['../structnvbio_1_1_suffix_core.html',1,'nvbio']]],
  ['suffixcore_3c_20stringtype_2c_20coordtype_2c_201u_20_3e',['SuffixCore&lt; StringType, CoordType, 1u &gt;',['../structnvbio_1_1_suffix_core_3_01_string_type_00_01_coord_type_00_011u_01_4.html',1,'nvbio']]],
  ['suffixcore_3c_20stringtype_2c_20coordtype_2c_202u_20_3e',['SuffixCore&lt; StringType, CoordType, 2u &gt;',['../structnvbio_1_1_suffix_core_3_01_string_type_00_01_coord_type_00_012u_01_4.html',1,'nvbio']]],
  ['suffixcore_3c_20stringtype_2c_20coordtype_2c_20vector_5ftraits_3c_20coordtype_20_3e_3a_3adim_20_3e',['SuffixCore&lt; StringType, CoordType, vector_traits&lt; CoordType &gt;::DIM &gt;',['../structnvbio_1_1_suffix_core.html',1,'nvbio']]],
  ['suffixset',['SuffixSet',['../structnvbio_1_1_suffix_set.html',1,'nvbio']]],
  ['suffixsetcore',['SuffixSetCore',['../structnvbio_1_1_suffix_set_core.html',1,'nvbio']]],
  ['suffixsetcore_3c_20sequencetype_2c_20suffixiterator_2c_201u_20_3e',['SuffixSetCore&lt; SequenceType, SuffixIterator, 1u &gt;',['../structnvbio_1_1_suffix_set_core_3_01_sequence_type_00_01_suffix_iterator_00_011u_01_4.html',1,'nvbio']]],
  ['suffixsetcore_3c_20sequencetype_2c_20suffixiterator_2c_202u_20_3e',['SuffixSetCore&lt; SequenceType, SuffixIterator, 2u &gt;',['../structnvbio_1_1_suffix_set_core_3_01_sequence_type_00_01_suffix_iterator_00_012u_01_4.html',1,'nvbio']]],
  ['suffixsetcore_3c_20sequencetype_2c_20suffixiterator_2c_20vector_5ftraits_3c_20std_3a_3aiterator_5ftraits_3c_20suffixiterator_20_3e_3a_3avalue_5ftype_20_3e_3a_3adim_20_3e',['SuffixSetCore&lt; SequenceType, SuffixIterator, vector_traits&lt; std::iterator_traits&lt; SuffixIterator &gt;::value_type &gt;::DIM &gt;',['../structnvbio_1_1_suffix_set_core.html',1,'nvbio']]],
  ['suffixtrie',['SuffixTrie',['../structnvbio_1_1_suffix_trie.html',1,'nvbio']]],
  ['sumtree',['SumTree',['../structnvbio_1_1_sum_tree.html',1,'nvbio']]],
  ['sw_5falignment_5fscore_5fdispatch',['sw_alignment_score_dispatch',['../structnvbio_1_1aln_1_1priv_1_1banded_1_1sw__alignment__score__dispatch.html',1,'nvbio::aln::priv::banded']]],
  ['sw_5falignment_5fscore_5fdispatch',['sw_alignment_score_dispatch',['../structnvbio_1_1aln_1_1priv_1_1sw__alignment__score__dispatch.html',1,'nvbio::aln::priv']]],
  ['sw_5falignment_5fscore_5fdispatch_3c_20band_5flen_2c_20type_2c_20patternblockingtag_2c_20symbol_5ftype_20_3e',['sw_alignment_score_dispatch&lt; BAND_LEN, TYPE, PatternBlockingTag, symbol_type &gt;',['../structnvbio_1_1aln_1_1priv_1_1sw__alignment__score__dispatch_3_01_b_a_n_d___l_e_n_00_01_t_y_p_e_11c3d4cf0b905442ede86a0c49f9d8b5.html',1,'nvbio::aln::priv']]],
  ['sw_5falignment_5fscore_5fdispatch_3c_20band_5flen_2c_20type_2c_20textblockingtag_2c_20symbol_5ftype_20_3e',['sw_alignment_score_dispatch&lt; BAND_LEN, TYPE, TextBlockingTag, symbol_type &gt;',['../structnvbio_1_1aln_1_1priv_1_1sw__alignment__score__dispatch_3_01_b_a_n_d___l_e_n_00_01_t_y_p_e_868c441b5689f47f78080d1fa63f8e64.html',1,'nvbio::aln::priv']]],
  ['sw_5fbandlen_5fselector',['sw_bandlen_selector',['../structnvbio_1_1aln_1_1priv_1_1sw__bandlen__selector.html',1,'nvbio::aln::priv']]],
  ['sw_5fbandlen_5fselector_3c_20type_2c_20dim_2c_20simd4u8_20_3e',['sw_bandlen_selector&lt; TYPE, DIM, simd4u8 &gt;',['../structnvbio_1_1aln_1_1priv_1_1sw__bandlen__selector_3_01_t_y_p_e_00_01_d_i_m_00_01simd4u8_01_4.html',1,'nvbio::aln::priv']]],
  ['swcheckpointcontext',['SWCheckpointContext',['../structnvbio_1_1aln_1_1priv_1_1_s_w_checkpoint_context.html',1,'nvbio::aln::priv']]],
  ['swcheckpointedscoringcontext',['SWCheckpointedScoringContext',['../structnvbio_1_1aln_1_1priv_1_1_s_w_checkpointed_scoring_context.html',1,'nvbio::aln::priv']]],
  ['swscoringcontext',['SWScoringContext',['../structnvbio_1_1aln_1_1priv_1_1_s_w_scoring_context.html',1,'nvbio::aln::priv']]],
  ['swsubmatrixcontext',['SWSubmatrixContext',['../structnvbio_1_1aln_1_1priv_1_1_s_w_submatrix_context.html',1,'nvbio::aln::priv']]],
  ['syncblocks',['syncblocks',['../structnvbio_1_1cuda_1_1syncblocks.html',1,'nvbio::cuda']]],
  ['syncblocks_5fstorage',['syncblocks_storage',['../structnvbio_1_1cuda_1_1syncblocks__storage.html',1,'nvbio::cuda']]]
];
