var searchData=
[
  ['backtracker',['Backtracker',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1_backtracker.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['backtracker_3c_20io_3a_3acigar_20_2a_20_3e',['Backtracker&lt; io::Cigar * &gt;',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1_backtracker.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['bad_5falloc',['bad_alloc',['../structnvbio_1_1bad__alloc.html',1,'nvbio']]],
  ['bam1_5fcore_5ft',['bam1_core_t',['../structbam1__core__t.html',1,'']]],
  ['bam1_5ft',['bam1_t',['../structbam1__t.html',1,'']]],
  ['bam_5falignment',['BAM_alignment',['../structnvbio_1_1io_1_1_b_a_m__alignment.html',1,'nvbio::io']]],
  ['bam_5falignment_5fbatch_5fraw',['BAM_alignment_batch_raw',['../struct_b_a_m__alignment__batch__raw.html',1,'']]],
  ['bam_5falignment_5fbatch_5fsoa',['BAM_alignment_batch_SoA',['../struct_b_a_m__alignment__batch___so_a.html',1,'']]],
  ['bam_5falignment_5fdata_5fblock',['BAM_alignment_data_block',['../structnvbio_1_1io_1_1_b_a_m__alignment__data__block.html',1,'nvbio::io']]],
  ['bam_5falignment_5fheader',['BAM_alignment_header',['../struct_b_a_m__alignment__header.html',1,'']]],
  ['bam_5falignment_5frecord',['BAM_alignment_record',['../struct_b_a_m__alignment__record.html',1,'']]],
  ['bam_5fcrq_5findex',['BAM_CRQ_index',['../struct_b_a_m___c_r_q__index.html',1,'']]],
  ['bam_5fhdr_5ft',['bam_hdr_t',['../structbam__hdr__t.html',1,'']]],
  ['bam_5fheader',['BAM_header',['../struct_b_a_m__header.html',1,'']]],
  ['bam_5fheader',['BAM_header',['../structnvbio_1_1io_1_1_b_a_m__header.html',1,'nvbio::io']]],
  ['bam_5fnaux_5findex',['BAM_NAUX_index',['../struct_b_a_m___n_a_u_x__index.html',1,'']]],
  ['bam_5fpileup1_5ft',['bam_pileup1_t',['../structbam__pileup1__t.html',1,'']]],
  ['bam_5freference',['BAM_reference',['../structnvbio_1_1io_1_1_b_a_m__reference.html',1,'nvbio::io']]],
  ['bamalignment',['BamAlignment',['../struct_bam_tools_1_1_bam_alignment.html',1,'BamTools']]],
  ['bamalignmentstream',['BAMAlignmentStream',['../structnvbio_1_1alndiff_1_1_b_a_m_alignment_stream.html',1,'nvbio::alndiff']]],
  ['bamoutput',['BamOutput',['../structnvbio_1_1io_1_1_bam_output.html',1,'nvbio::io']]],
  ['bamreader',['BamReader',['../class_bam_tools_1_1_bam_reader.html',1,'BamTools']]],
  ['bamreaderprivate',['BamReaderPrivate',['../struct_bam_reader_1_1_bam_reader_private.html',1,'BamTools::BamReader']]],
  ['bamwriter',['BamWriter',['../class_bam_tools_1_1_bam_writer.html',1,'BamTools']]],
  ['bamwriterprivate',['BamWriterPrivate',['../struct_bam_writer_1_1_bam_writer_private.html',1,'BamTools::BamWriter']]],
  ['banded_5falignment_5fcheckpointed_5fdispatch',['banded_alignment_checkpointed_dispatch',['../structnvbio_1_1aln_1_1priv_1_1banded__alignment__checkpointed__dispatch.html',1,'nvbio::aln::priv']]],
  ['banded_5falignment_5fscore_5fdispatch',['banded_alignment_score_dispatch',['../structnvbio_1_1aln_1_1priv_1_1banded__alignment__score__dispatch.html',1,'nvbio::aln::priv']]],
  ['bandedscoreunit',['BandedScoreUnit',['../structnvbio_1_1aln_1_1_banded_score_unit.html',1,'nvbio::aln']]],
  ['base_5frep_5ftag',['base_rep_tag',['../structnvbio_1_1simd4u8_1_1base__rep__tag.html',1,'nvbio::simd4u8']]],
  ['basescoringpipelinestate',['BaseScoringPipelineState',['../structnvbio_1_1bowtie2_1_1cuda_1_1_base_scoring_pipeline_state.html',1,'nvbio::bowtie2::cuda']]],
  ['batchedalignmentscore',['BatchedAlignmentScore',['../structnvbio_1_1aln_1_1_batched_alignment_score.html',1,'nvbio::aln']]],
  ['batchedalignmentscore_3c_20stream_5ftype_2c_20devicestagedthreadscheduler_20_3e',['BatchedAlignmentScore&lt; stream_type, DeviceStagedThreadScheduler &gt;',['../structnvbio_1_1aln_1_1_batched_alignment_score_3_01stream__type_00_01_device_staged_thread_scheduler_01_4.html',1,'nvbio::aln']]],
  ['batchedalignmentscore_3c_20stream_5ftype_2c_20devicethreadblockscheduler_3c_20blockdim_2c_20minblocks_20_3e_20_3e',['BatchedAlignmentScore&lt; stream_type, DeviceThreadBlockScheduler&lt; BLOCKDIM, MINBLOCKS &gt; &gt;',['../structnvbio_1_1aln_1_1_batched_alignment_score_3_01stream__type_00_01_device_thread_block_schedu1516e060a2409f4344f97c75c3ae9775.html',1,'nvbio::aln']]],
  ['batchedalignmentscore_3c_20stream_5ftype_2c_20devicewarpscheduler_20_3e',['BatchedAlignmentScore&lt; stream_type, DeviceWarpScheduler &gt;',['../structnvbio_1_1aln_1_1_batched_alignment_score_3_01stream__type_00_01_device_warp_scheduler_01_4.html',1,'nvbio::aln']]],
  ['batchedalignmentscore_3c_20stream_5ftype_2c_20hostthreadscheduler_20_3e',['BatchedAlignmentScore&lt; stream_type, HostThreadScheduler &gt;',['../structnvbio_1_1aln_1_1_batched_alignment_score_3_01stream__type_00_01_host_thread_scheduler_01_4.html',1,'nvbio::aln']]],
  ['batchedalignmenttraceback',['BatchedAlignmentTraceback',['../structnvbio_1_1aln_1_1_batched_alignment_traceback.html',1,'nvbio::aln']]],
  ['batchedalignmenttraceback_3c_20checkpoints_2c_20stream_5ftype_2c_20devicethreadblockscheduler_3c_20blockdim_2c_20minblocks_20_3e_20_3e',['BatchedAlignmentTraceback&lt; CHECKPOINTS, stream_type, DeviceThreadBlockScheduler&lt; BLOCKDIM, MINBLOCKS &gt; &gt;',['../structnvbio_1_1aln_1_1_batched_alignment_traceback_3_01_c_h_e_c_k_p_o_i_n_t_s_00_01stream__type_e816adbf5880de2a7fcabf42808ba443.html',1,'nvbio::aln']]],
  ['batchedbandedalignmentscore',['BatchedBandedAlignmentScore',['../structnvbio_1_1aln_1_1_batched_banded_alignment_score.html',1,'nvbio::aln']]],
  ['batchedbandedalignmentscore_3c_20band_5flen_2c_20stream_5ftype_2c_20devicestagedthreadscheduler_20_3e',['BatchedBandedAlignmentScore&lt; BAND_LEN, stream_type, DeviceStagedThreadScheduler &gt;',['../structnvbio_1_1aln_1_1_batched_banded_alignment_score_3_01_b_a_n_d___l_e_n_00_01stream__type_00_eeba9ca5ffeeeeb87c6cb1ef40282f90.html',1,'nvbio::aln']]],
  ['batchedbandedalignmentscore_3c_20band_5flen_2c_20stream_5ftype_2c_20devicethreadblockscheduler_3c_20blockdim_2c_20minblocks_20_3e_20_3e',['BatchedBandedAlignmentScore&lt; BAND_LEN, stream_type, DeviceThreadBlockScheduler&lt; BLOCKDIM, MINBLOCKS &gt; &gt;',['../structnvbio_1_1aln_1_1_batched_banded_alignment_score_3_01_b_a_n_d___l_e_n_00_01stream__type_00_92a6a56ac1e8212dc58c3b10191e5fd1.html',1,'nvbio::aln']]],
  ['batchedbandedalignmentscore_3c_20band_5flen_2c_20stream_5ftype_2c_20hostthreadscheduler_20_3e',['BatchedBandedAlignmentScore&lt; BAND_LEN, stream_type, HostThreadScheduler &gt;',['../structnvbio_1_1aln_1_1_batched_banded_alignment_score_3_01_b_a_n_d___l_e_n_00_01stream__type_00_01_host_thread_scheduler_01_4.html',1,'nvbio::aln']]],
  ['batchedbandedalignmenttraceback',['BatchedBandedAlignmentTraceback',['../structnvbio_1_1aln_1_1_batched_banded_alignment_traceback.html',1,'nvbio::aln']]],
  ['batchedbandedalignmenttraceback_3c_20band_5flen_2c_20checkpoints_2c_20stream_5ftype_2c_20devicethreadscheduler_20_3e',['BatchedBandedAlignmentTraceback&lt; BAND_LEN, CHECKPOINTS, stream_type, DeviceThreadScheduler &gt;',['../structnvbio_1_1aln_1_1_batched_banded_alignment_traceback_3_01_b_a_n_d___l_e_n_00_01_c_h_e_c_k_pdd42a2f4700aad7eacd1d840a49ae8fc.html',1,'nvbio::aln']]],
  ['bcf1_5ft',['bcf1_t',['../structbcf1__t.html',1,'']]],
  ['bcf_5fdec_5ft',['bcf_dec_t',['../structbcf__dec__t.html',1,'']]],
  ['bcf_5ffmt_5ft',['bcf_fmt_t',['../structbcf__fmt__t.html',1,'']]],
  ['bcf_5fhdr_5ft',['bcf_hdr_t',['../structbcf__hdr__t.html',1,'']]],
  ['bcf_5fhrec_5ft',['bcf_hrec_t',['../structbcf__hrec__t.html',1,'']]],
  ['bcf_5fidinfo_5ft',['bcf_idinfo_t',['../structbcf__idinfo__t.html',1,'']]],
  ['bcf_5fidpair_5ft',['bcf_idpair_t',['../structbcf__idpair__t.html',1,'']]],
  ['bcf_5finfo_5ft',['bcf_info_t',['../structbcf__info__t.html',1,'']]],
  ['bcf_5fsr_5ft',['bcf_sr_t',['../structbcf__sr__t.html',1,'']]],
  ['bcf_5fsrs_5ft',['bcf_srs_t',['../structbcf__srs__t.html',1,'']]],
  ['best2sink',['Best2Sink',['../structnvbio_1_1aln_1_1_best2_sink.html',1,'nvbio::aln']]],
  ['bestalignments',['BestAlignments',['../structnvbio_1_1io_1_1_best_alignments.html',1,'nvbio::io']]],
  ['bestanchorscorestream',['BestAnchorScoreStream',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1_best_anchor_score_stream.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['bestapproxscoringpipelinestate',['BestApproxScoringPipelineState',['../structnvbio_1_1bowtie2_1_1cuda_1_1_best_approx_scoring_pipeline_state.html',1,'nvbio::bowtie2::cuda']]],
  ['bestoppositescorestream',['BestOppositeScoreStream',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1_best_opposite_score_stream.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['bestpairedalignments',['BestPairedAlignments',['../structnvbio_1_1io_1_1_best_paired_alignments.html',1,'nvbio::io']]],
  ['bestscorestream',['BestScoreStream',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1_best_score_stream.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['bestsink',['BestSink',['../structnvbio_1_1aln_1_1_best_sink.html',1,'nvbio::aln']]],
  ['bestsink_3c_20int32_20_3e',['BestSink&lt; int32 &gt;',['../structnvbio_1_1aln_1_1_best_sink.html',1,'nvbio::aln']]],
  ['bestsink_3c_20simd4u8_20_3e',['BestSink&lt; simd4u8 &gt;',['../structnvbio_1_1aln_1_1_best_sink_3_01simd4u8_01_4.html',1,'nvbio::aln']]],
  ['besttracebackstream',['BestTracebackStream',['../structnvbio_1_1bowtie2_1_1cuda_1_1detail_1_1_best_traceback_stream.html',1,'nvbio::bowtie2::cuda::detail']]],
  ['bgzf',['BGZF',['../struct_b_g_z_f.html',1,'']]],
  ['bgzf_5fextra_5fdata',['bgzf_extra_data',['../structnvbio_1_1io_1_1_b_g_z_f_compressor_1_1bgzf__extra__data.html',1,'nvbio::io::BGZFCompressor']]],
  ['bgzf_5fmtaux_5ft',['bgzf_mtaux_t',['../structbgzf__mtaux__t.html',1,'']]],
  ['bgzfcompressor',['BGZFCompressor',['../structnvbio_1_1io_1_1_b_g_z_f_compressor.html',1,'nvbio::io']]],
  ['bgzfdata',['BgzfData',['../struct_bam_tools_1_1_bgzf_data.html',1,'BamTools']]],
  ['bgzfilewriter',['BGZFileWriter',['../structnvbio_1_1_b_g_z_file_writer.html',1,'nvbio']]],
  ['bgzfthread',['BgzfThread',['../struct_bam_tools_1_1_bgzf_thread.html',1,'BamTools']]],
  ['bgzidx1_5ft',['bgzidx1_t',['../structbgzidx1__t.html',1,'']]],
  ['binary_5fswitch',['binary_switch',['../structnvbio_1_1binary__switch.html',1,'nvbio']]],
  ['binary_5fswitch_3c_20a_2c_20b_2c_200_20_3e',['binary_switch&lt; A, B, 0 &gt;',['../structnvbio_1_1binary__switch_3_01_a_00_01_b_00_010_01_4.html',1,'nvbio']]],
  ['binary_5ftransform_5fiterator',['binary_transform_iterator',['../structnvbio_1_1binary__transform__iterator.html',1,'nvbio']]],
  ['binarycast',['BinaryCast',['../unionnvbio_1_1_binary_cast.html',1,'nvbio']]],
  ['bind_5ffirst_5ffunctor',['bind_first_functor',['../structnvbio_1_1bind__first__functor.html',1,'nvbio']]],
  ['bind_5fsecond_5ffunctor',['bind_second_functor',['../structnvbio_1_1bind__second__functor.html',1,'nvbio']]],
  ['bins_5ft',['bins_t',['../structbins__t.html',1,'']]],
  ['bits',['Bits',['../structnvbio_1_1priv_1_1_bits.html',1,'nvbio::priv']]],
  ['block_5fstrided_5fiterator',['block_strided_iterator',['../structnvbio_1_1block__strided__iterator.html',1,'nvbio']]],
  ['bloom_5ffilter',['bloom_filter',['../structnvbio_1_1bloom__filter.html',1,'nvbio']]],
  ['bns_5ffiles_5fmismatch',['bns_files_mismatch',['../structnvbio_1_1bns__files__mismatch.html',1,'nvbio']]],
  ['bns_5ffopen_5ffailure',['bns_fopen_failure',['../structnvbio_1_1bns__fopen__failure.html',1,'nvbio']]],
  ['bnt',['BNT',['../structnvbio_1_1io_1_1_b_n_t.html',1,'nvbio::io']]],
  ['bntamb',['BNTAmb',['../structnvbio_1_1_b_n_t_amb.html',1,'nvbio']]],
  ['bntanndata',['BNTAnnData',['../structnvbio_1_1_b_n_t_ann_data.html',1,'nvbio']]],
  ['bntanninfo',['BNTAnnInfo',['../structnvbio_1_1_b_n_t_ann_info.html',1,'nvbio']]],
  ['bntinfo',['BNTInfo',['../structnvbio_1_1_b_n_t_info.html',1,'nvbio']]],
  ['bntseq',['BNTSeq',['../structnvbio_1_1_b_n_t_seq.html',1,'nvbio']]],
  ['bntseqloader',['BNTSeqLoader',['../structnvbio_1_1_b_n_t_seq_loader.html',1,'nvbio']]],
  ['body_5fobject',['body_object',['../structnvbio_1_1html_1_1body__object.html',1,'nvbio::html']]],
  ['booleanstats',['BooleanStats',['../structnvbio_1_1alndiff_1_1_boolean_stats.html',1,'nvbio::alndiff']]],
  ['bowtiemapq2',['BowtieMapq2',['../structnvbio_1_1bowtie2_1_1cuda_1_1_bowtie_mapq2.html',1,'nvbio::bowtie2::cuda']]],
  ['bowtiemapq3',['BowtieMapq3',['../structnvbio_1_1bowtie2_1_1cuda_1_1_bowtie_mapq3.html',1,'nvbio::bowtie2::cuda']]],
  ['bufferedtextfile',['BufferedTextFile',['../classnvbio_1_1io_1_1_buffered_text_file.html',1,'nvbio::io']]],
  ['bwtbgzwriter',['BWTBGZWriter',['../structnvbio_1_1_b_w_t_b_g_z_writer.html',1,'nvbio']]],
  ['bwteblock',['BWTEBlock',['../structnvbio_1_1_b_w_t_e_block.html',1,'nvbio']]],
  ['bwtecontext',['BWTEContext',['../structnvbio_1_1_b_w_t_e_context.html',1,'nvbio']]],
  ['bwtlz4writer',['BWTLZ4Writer',['../structnvbio_1_1_b_w_t_l_z4_writer.html',1,'nvbio']]],
  ['bwtparams',['BWTParams',['../structnvbio_1_1_b_w_t_params.html',1,'nvbio']]]
];
