var searchData=
[
  ['gather_5ffunctor',['gather_functor',['../structnvbio_1_1gather__functor.html',1,'nvbio']]],
  ['genome_5finfixes',['genome_infixes',['../structgenome__infixes.html',1,'']]],
  ['genome_5floc',['genome_loc',['../structgenome__loc.html',1,'']]],
  ['get_5fchar_5ffunctor',['get_char_functor',['../structnvbio_1_1get__char__functor.html',1,'nvbio']]],
  ['get_5fglobal_5fid',['get_global_id',['../structget__global__id.html',1,'']]],
  ['get_5fkmer_5freg_5fid',['get_kmer_reg_id',['../structget__kmer__reg__id.html',1,'']]],
  ['get_5fkmer_5fseq_5fid',['get_kmer_seq_id',['../structget__kmer__seq__id.html',1,'']]],
  ['get_5fkmer_5fsize',['get_kmer_size',['../structget__kmer__size.html',1,'']]],
  ['get_5fprefix_5fglobal_5fid',['get_prefix_global_id',['../structget__prefix__global__id.html',1,'']]],
  ['get_5fprefix_5fglobal_5fid_5fby_5fidx',['get_prefix_global_id_by_idx',['../structget__prefix__global__id__by__idx.html',1,'']]],
  ['get_5fsuffix_5fglobal_5fid_5fby_5fidx',['get_suffix_global_id_by_idx',['../structget__suffix__global__id__by__idx.html',1,'']]],
  ['global_5fset_5fsuffix_5fword_5ffunctor',['global_set_suffix_word_functor',['../structnvbio_1_1priv_1_1global__set__suffix__word__functor.html',1,'nvbio::priv']]],
  ['global_5fto_5fsorted_5fid',['global_to_sorted_id',['../structglobal__to__sorted__id.html',1,'']]],
  ['global_5fto_5fuid',['global_to_uid',['../structglobal__to__uid.html',1,'']]],
  ['gotoh_5falignment_5fscore_5fdispatch',['gotoh_alignment_score_dispatch',['../structnvbio_1_1aln_1_1priv_1_1gotoh__alignment__score__dispatch.html',1,'nvbio::aln::priv']]],
  ['gotoh_5falignment_5fscore_5fdispatch',['gotoh_alignment_score_dispatch',['../structnvbio_1_1aln_1_1priv_1_1banded_1_1gotoh__alignment__score__dispatch.html',1,'nvbio::aln::priv::banded']]],
  ['gotoh_5falignment_5fscore_5fdispatch_3c_20band_5flen_2c_20type_2c_20patternblockingtag_2c_20symbol_5ftype_20_3e',['gotoh_alignment_score_dispatch&lt; BAND_LEN, TYPE, PatternBlockingTag, symbol_type &gt;',['../structnvbio_1_1aln_1_1priv_1_1gotoh__alignment__score__dispatch_3_01_b_a_n_d___l_e_n_00_01_t_y_p09305c5618ba9afd6c01d19efb350726.html',1,'nvbio::aln::priv']]],
  ['gotoh_5falignment_5fscore_5fdispatch_3c_20band_5flen_2c_20type_2c_20textblockingtag_2c_20symbol_5ftype_20_3e',['gotoh_alignment_score_dispatch&lt; BAND_LEN, TYPE, TextBlockingTag, symbol_type &gt;',['../structnvbio_1_1aln_1_1priv_1_1gotoh__alignment__score__dispatch_3_01_b_a_n_d___l_e_n_00_01_t_y_pf6908c798e2b3cde6dff52ca44db491e.html',1,'nvbio::aln::priv']]],
  ['gotoh_5fbandlen_5fselector',['gotoh_bandlen_selector',['../structnvbio_1_1aln_1_1priv_1_1gotoh__bandlen__selector.html',1,'nvbio::aln::priv']]],
  ['gotoh_5fbandlen_5fselector_3c_20type_2c_20dim_2c_20simd4u8_20_3e',['gotoh_bandlen_selector&lt; TYPE, DIM, simd4u8 &gt;',['../structnvbio_1_1aln_1_1priv_1_1gotoh__bandlen__selector_3_01_t_y_p_e_00_01_d_i_m_00_01simd4u8_01_4.html',1,'nvbio::aln::priv']]],
  ['gotoh_5fuse_5fvectorization',['gotoh_use_vectorization',['../structnvbio_1_1aln_1_1priv_1_1gotoh__use__vectorization.html',1,'nvbio::aln::priv']]],
  ['gotoh_5fuse_5fvectorization_3c_20vector_5fview_3c_20const_20t_20_2a_20_3e_20_3e',['gotoh_use_vectorization&lt; vector_view&lt; const T * &gt; &gt;',['../structnvbio_1_1aln_1_1priv_1_1gotoh__use__vectorization_3_01vector__view_3_01const_01_t_01_5_01_4_01_4.html',1,'nvbio::aln::priv']]],
  ['gotoh_5fuse_5fvectorization_3c_20vector_5fview_3c_20t_20_2a_20_3e_20_3e',['gotoh_use_vectorization&lt; vector_view&lt; T * &gt; &gt;',['../structnvbio_1_1aln_1_1priv_1_1gotoh__use__vectorization_3_01vector__view_3_01_t_01_5_01_4_01_4.html',1,'nvbio::aln::priv']]],
  ['gotohaligner',['GotohAligner',['../structnvbio_1_1aln_1_1_gotoh_aligner.html',1,'nvbio::aln']]],
  ['gotohcheckpointcontext',['GotohCheckpointContext',['../structnvbio_1_1aln_1_1priv_1_1banded_1_1_gotoh_checkpoint_context.html',1,'nvbio::aln::priv::banded']]],
  ['gotohcheckpointcontext',['GotohCheckpointContext',['../structnvbio_1_1aln_1_1priv_1_1_gotoh_checkpoint_context.html',1,'nvbio::aln::priv']]],
  ['gotohcheckpointedscoringcontext',['GotohCheckpointedScoringContext',['../structnvbio_1_1aln_1_1priv_1_1banded_1_1_gotoh_checkpointed_scoring_context.html',1,'nvbio::aln::priv::banded']]],
  ['gotohcheckpointedscoringcontext',['GotohCheckpointedScoringContext',['../structnvbio_1_1aln_1_1priv_1_1_gotoh_checkpointed_scoring_context.html',1,'nvbio::aln::priv']]],
  ['gotohscoringcontext',['GotohScoringContext',['../structnvbio_1_1aln_1_1priv_1_1_gotoh_scoring_context.html',1,'nvbio::aln::priv']]],
  ['gotohscoringcontext',['GotohScoringContext',['../structnvbio_1_1aln_1_1priv_1_1banded_1_1_gotoh_scoring_context.html',1,'nvbio::aln::priv::banded']]],
  ['gotohsubmatrixcontext',['GotohSubmatrixContext',['../structnvbio_1_1aln_1_1priv_1_1_gotoh_submatrix_context.html',1,'nvbio::aln::priv']]],
  ['gotohsubmatrixcontext',['GotohSubmatrixContext',['../structnvbio_1_1aln_1_1priv_1_1banded_1_1_gotoh_submatrix_context.html',1,'nvbio::aln::priv::banded']]],
  ['gotohtag',['GotohTag',['../structnvbio_1_1aln_1_1_gotoh_tag.html',1,'nvbio::aln']]],
  ['graph_5ffunctor',['graph_functor',['../structgraph__functor.html',1,'']]],
  ['gz_5fheader_5fs',['gz_header_s',['../structgz__header__s.html',1,'']]],
  ['gz_5fstate',['gz_state',['../structgz__state.html',1,'']]],
  ['gzfile_5fs',['gzFile_s',['../structgz_file__s.html',1,'']]],
  ['gzipcompressor',['GzipCompressor',['../structnvbio_1_1io_1_1_gzip_compressor.html',1,'nvbio::io']]],
  ['gzoutputfile',['GZOutputFile',['../structnvbio_1_1_g_z_output_file.html',1,'nvbio']]]
];
