var searchData=
[
  ['range_5fsize',['range_size',['../structnvbio_1_1fmindex_1_1range__size.html',1,'nvbio::fmindex']]],
  ['range_5fsize',['range_size',['../structnvbio_1_1mem_1_1range__size.html',1,'nvbio::mem']]],
  ['range_5fsize',['range_size',['../structnvbio_1_1qgram_1_1range__size.html',1,'nvbio::qgram']]],
  ['rank_5fdictionary',['rank_dictionary',['../structnvbio_1_1rank__dictionary.html',1,'nvbio']]],
  ['rank_5ffunctor',['rank_functor',['../structnvbio_1_1fmindex_1_1rank__functor.html',1,'nvbio::fmindex']]],
  ['rank_5fspan_5fsize',['rank_span_size',['../structnvbio_1_1mem_1_1rank__span__size.html',1,'nvbio::mem']]],
  ['rank_5fstring_5fid',['rank_string_id',['../structnvbio_1_1mem_1_1rank__string__id.html',1,'nvbio::mem']]],
  ['rank_5fword_5ftraits',['rank_word_traits',['../structnvbio_1_1rank__word__traits.html',1,'nvbio']]],
  ['rank_5fword_5ftraits_3c_202_2c_20uint32_20_3e',['rank_word_traits&lt; 2, uint32 &gt;',['../structnvbio_1_1rank__word__traits_3_012_00_01uint32_01_4.html',1,'nvbio']]],
  ['rank_5fword_5ftraits_3c_202_2c_20uint64_20_3e',['rank_word_traits&lt; 2, uint64 &gt;',['../structnvbio_1_1rank__word__traits_3_012_00_01uint64_01_4.html',1,'nvbio']]],
  ['rank_5fword_5ftraits_3c_204_2c_20uint32_20_3e',['rank_word_traits&lt; 4, uint32 &gt;',['../structnvbio_1_1rank__word__traits_3_014_00_01uint32_01_4.html',1,'nvbio']]],
  ['rank_5fword_5ftraits_3c_204_2c_20uint64_20_3e',['rank_word_traits&lt; 4, uint64 &gt;',['../structnvbio_1_1rank__word__traits_3_014_00_01uint64_01_4.html',1,'nvbio']]],
  ['rank_5fword_5ftraits_3c_208_2c_20uint32_20_3e',['rank_word_traits&lt; 8, uint32 &gt;',['../structnvbio_1_1rank__word__traits_3_018_00_01uint32_01_4.html',1,'nvbio']]],
  ['rank_5fword_5ftraits_3c_208_2c_20uint64_20_3e',['rank_word_traits&lt; 8, uint64 &gt;',['../structnvbio_1_1rank__word__traits_3_018_00_01uint64_01_4.html',1,'nvbio']]],
  ['read_5finfixes',['read_infixes',['../structread__infixes.html',1,'']]],
  ['read_5fstring',['read_string',['../structnvbio_1_1io_1_1read__string.html',1,'nvbio::io']]],
  ['readdata',['ReadData',['../structnvbio_1_1io_1_1_read_data.html',1,'nvbio::io']]],
  ['readdatadevice',['ReadDataDevice',['../structnvbio_1_1io_1_1_read_data_device.html',1,'nvbio::io']]],
  ['readdatafile',['ReadDataFile',['../structnvbio_1_1io_1_1_read_data_file.html',1,'nvbio::io']]],
  ['readdatafile_5fbam',['ReadDataFile_BAM',['../structnvbio_1_1io_1_1_read_data_file___b_a_m.html',1,'nvbio::io']]],
  ['readdatafile_5ffastq_5fgz',['ReadDataFile_FASTQ_gz',['../structnvbio_1_1io_1_1_read_data_file___f_a_s_t_q__gz.html',1,'nvbio::io']]],
  ['readdatafile_5ffastq_5fparser',['ReadDataFile_FASTQ_parser',['../structnvbio_1_1io_1_1_read_data_file___f_a_s_t_q__parser.html',1,'nvbio::io']]],
  ['readdatafile_5fsam',['ReadDataFile_SAM',['../structnvbio_1_1io_1_1_read_data_file___s_a_m.html',1,'nvbio::io']]],
  ['readdatafile_5ftxt',['ReadDataFile_TXT',['../structnvbio_1_1io_1_1_read_data_file___t_x_t.html',1,'nvbio::io']]],
  ['readdatafile_5ftxt_5fgz',['ReadDataFile_TXT_gz',['../structnvbio_1_1io_1_1_read_data_file___t_x_t__gz.html',1,'nvbio::io']]],
  ['readdataram',['ReadDataRAM',['../structnvbio_1_1io_1_1_read_data_r_a_m.html',1,'nvbio::io']]],
  ['readdatastream',['ReadDataStream',['../structnvbio_1_1io_1_1_read_data_stream.html',1,'nvbio::io']]],
  ['readdataview',['ReadDataView',['../structnvbio_1_1io_1_1_read_data_view.html',1,'nvbio::io']]],
  ['readhitbinder',['ReadHitBinder',['../structnvbio_1_1bowtie2_1_1cuda_1_1_read_hit_binder.html',1,'nvbio::bowtie2::cuda']]],
  ['readhitreference',['ReadHitReference',['../structnvbio_1_1bowtie2_1_1cuda_1_1_read_hit_reference.html',1,'nvbio::bowtie2::cuda']]],
  ['readhitsbinder',['ReadHitsBinder',['../structnvbio_1_1bowtie2_1_1cuda_1_1_read_hits_binder.html',1,'nvbio::bowtie2::cuda']]],
  ['readhitsindex',['ReadHitsIndex',['../structnvbio_1_1bowtie2_1_1cuda_1_1_read_hits_index.html',1,'nvbio::bowtie2::cuda']]],
  ['readhitsindex',['ReadHitsIndex',['../structcufmi_1_1bowtie2_1_1cuda_1_1_read_hits_index.html',1,'cufmi::bowtie2::cuda']]],
  ['readhitsindexdeviceview',['ReadHitsIndexDeviceView',['../structcufmi_1_1bowtie2_1_1cuda_1_1_read_hits_index_device_view.html',1,'cufmi::bowtie2::cuda']]],
  ['readhitsindexdeviceview',['ReadHitsIndexDeviceView',['../structnvbio_1_1bowtie2_1_1cuda_1_1_read_hits_index_device_view.html',1,'nvbio::bowtie2::cuda']]],
  ['readhitsreference',['ReadHitsReference',['../structcufmi_1_1bowtie2_1_1cuda_1_1_read_hits_reference.html',1,'cufmi::bowtie2::cuda']]],
  ['readhitsreference',['ReadHitsReference',['../structnvbio_1_1bowtie2_1_1cuda_1_1_read_hits_reference.html',1,'nvbio::bowtie2::cuda']]],
  ['readhitsreference_3c_20read_5fhits_5findex_5ftype_2c_20hits_5fstorage_5ftype_20_3e',['ReadHitsReference&lt; read_hits_index_type, hits_storage_type &gt;',['../structcufmi_1_1bowtie2_1_1cuda_1_1_read_hits_reference.html',1,'cufmi::bowtie2::cuda']]],
  ['readloader',['ReadLoader',['../structnvbio_1_1_read_loader.html',1,'nvbio']]],
  ['readloader_3c_20read_5fbatch_5ftype_2c_20lmem_5fcache_5ftype_20_3e',['ReadLoader&lt; read_batch_type, lmem_cache_type &gt;',['../structnvbio_1_1_read_loader.html',1,'nvbio']]],
  ['readreference',['ReadReference',['../structcufmi_1_1bowtie2_1_1cuda_1_1_read_reference.html',1,'cufmi::bowtie2::cuda']]],
  ['readsdef',['ReadsDef',['../structnvbio_1_1bowtie2_1_1cuda_1_1_reads_def.html',1,'nvbio::bowtie2::cuda']]],
  ['readstream',['ReadStream',['../structnvbio_1_1_read_stream.html',1,'nvbio']]],
  ['readstreamqualities',['ReadStreamQualities',['../structnvbio_1_1_read_stream_qualities.html',1,'nvbio']]],
  ['reducebestapproxcontext',['ReduceBestApproxContext',['../structnvbio_1_1bowtie2_1_1cuda_1_1_reduce_best_approx_context.html',1,'nvbio::bowtie2::cuda']]],
  ['reducebestexactcontext',['ReduceBestExactContext',['../structnvbio_1_1bowtie2_1_1cuda_1_1_reduce_best_exact_context.html',1,'nvbio::bowtie2::cuda']]],
  ['ref_5fentry',['ref_entry',['../structref__entry.html',1,'']]],
  ['refdata',['RefData',['../struct_bam_tools_1_1_ref_data.html',1,'BamTools']]],
  ['refedit',['RefEdit',['../struct_bam_tools_1_1_ref_edit.html',1,'BamTools']]],
  ['reference_5fcache',['Reference_cache',['../structnvbio_1_1aln_1_1priv_1_1_reference__cache.html',1,'nvbio::aln::priv']]],
  ['reference_5fcache_3c_2015u_20_3e',['Reference_cache&lt; 15u &gt;',['../structnvbio_1_1aln_1_1priv_1_1_reference__cache_3_0115u_01_4.html',1,'nvbio::aln::priv']]],
  ['reference_5fcache_3c_203u_20_3e',['Reference_cache&lt; 3u &gt;',['../structnvbio_1_1aln_1_1priv_1_1_reference__cache_3_013u_01_4.html',1,'nvbio::aln::priv']]],
  ['reference_5fcache_3c_205u_20_3e',['Reference_cache&lt; 5u &gt;',['../structnvbio_1_1aln_1_1priv_1_1_reference__cache_3_015u_01_4.html',1,'nvbio::aln::priv']]],
  ['reference_5fcache_3c_207u_20_3e',['Reference_cache&lt; 7u &gt;',['../structnvbio_1_1aln_1_1priv_1_1_reference__cache_3_017u_01_4.html',1,'nvbio::aln::priv']]],
  ['reference_5fsubtype',['reference_subtype',['../structnvbio_1_1reference__subtype.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20const_20t_20_2a_20_3e',['reference_subtype&lt; const T * &gt;',['../structnvbio_1_1reference__subtype_3_01const_01_t_01_5_01_4.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20null_5ftype_20_3e',['reference_subtype&lt; null_type &gt;',['../structnvbio_1_1reference__subtype_3_01null__type_01_4.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20t_20_2a_20_3e',['reference_subtype&lt; T * &gt;',['../structnvbio_1_1reference__subtype_3_01_t_01_5_01_4.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20typename_20hitqueuestype_3a_3aindex_5fstorage_5ftype_20_3e',['reference_subtype&lt; typename HitQueuesType::index_storage_type &gt;',['../structnvbio_1_1reference__subtype.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20typename_20hitqueuestype_3a_3aloc_5fstorage_5ftype_20_3e',['reference_subtype&lt; typename HitQueuesType::loc_storage_type &gt;',['../structnvbio_1_1reference__subtype.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20typename_20hitqueuestype_3a_3ascore_5fstorage_5ftype_20_3e',['reference_subtype&lt; typename HitQueuesType::score_storage_type &gt;',['../structnvbio_1_1reference__subtype.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20typename_20hitqueuestype_3a_3aseed_5fstorage_5ftype_20_3e',['reference_subtype&lt; typename HitQueuesType::seed_storage_type &gt;',['../structnvbio_1_1reference__subtype.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20typename_20hitqueuestype_3a_3asink_5fstorage_5ftype_20_3e',['reference_subtype&lt; typename HitQueuesType::sink_storage_type &gt;',['../structnvbio_1_1reference__subtype.html',1,'nvbio']]],
  ['reference_5fsubtype_3c_20typename_20hitqueuestype_3a_3assa_5fstorage_5ftype_20_3e',['reference_subtype&lt; typename HitQueuesType::ssa_storage_type &gt;',['../structnvbio_1_1reference__subtype.html',1,'nvbio']]],
  ['referenceindex',['ReferenceIndex',['../struct_bam_tools_1_1_reference_index.html',1,'BamTools']]],
  ['refs_5ft',['refs_t',['../structrefs__t.html',1,'']]],
  ['region1_5ft',['region1_t',['../structregion1__t.html',1,'']]],
  ['remove_5fsingletons',['remove_singletons',['../structnvbio_1_1priv_1_1remove__singletons.html',1,'nvbio::priv']]],
  ['reverse_5ffunctor',['reverse_functor',['../structnvbio_1_1reverse__functor.html',1,'nvbio']]],
  ['reversexform',['ReverseXform',['../structnvbio_1_1_reverse_xform.html',1,'nvbio']]],
  ['right_5fmem_5ffunctor',['right_mem_functor',['../structnvbio_1_1mem_1_1right__mem__functor.html',1,'nvbio::mem']]],
  ['roundedqualcost',['RoundedQualCost',['../structnvbio_1_1bowtie2_1_1cuda_1_1_rounded_qual_cost.html',1,'nvbio::bowtie2::cuda']]],
  ['runtime_5ferror',['runtime_error',['../structnvbio_1_1runtime__error.html',1,'nvbio']]]
];
