var searchData=
[
  ['hamming_5falignment_5fscore_5fdispatch',['hamming_alignment_score_dispatch',['../structnvbio_1_1aln_1_1priv_1_1hamming__alignment__score__dispatch.html',1,'nvbio::aln::priv']]],
  ['hamming_5falignment_5fscore_5fdispatch_3c_20band_5flen_2c_20type_2c_20patternblockingtag_2c_20symbol_5ftype_20_3e',['hamming_alignment_score_dispatch&lt; BAND_LEN, TYPE, PatternBlockingTag, symbol_type &gt;',['../structnvbio_1_1aln_1_1priv_1_1hamming__alignment__score__dispatch_3_01_b_a_n_d___l_e_n_00_01_t_y061d85f9ae5d80599bd1fab6745d0ba2.html',1,'nvbio::aln::priv']]],
  ['hamming_5falignment_5fscore_5fdispatch_3c_20band_5flen_2c_20type_2c_20textblockingtag_2c_20symbol_5ftype_20_3e',['hamming_alignment_score_dispatch&lt; BAND_LEN, TYPE, TextBlockingTag, symbol_type &gt;',['../structnvbio_1_1aln_1_1priv_1_1hamming__alignment__score__dispatch_3_01_b_a_n_d___l_e_n_00_01_t_yf77786b2c119d8b6224936785cd0119e.html',1,'nvbio::aln::priv']]],
  ['hamming_5fbandlen_5fselector',['hamming_bandlen_selector',['../structnvbio_1_1aln_1_1priv_1_1hamming__bandlen__selector.html',1,'nvbio::aln::priv']]],
  ['hamming_5fbandlen_5fselector_3c_20type_2c_20dim_2c_20simd4u8_20_3e',['hamming_bandlen_selector&lt; TYPE, DIM, simd4u8 &gt;',['../structnvbio_1_1aln_1_1priv_1_1hamming__bandlen__selector_3_01_t_y_p_e_00_01_d_i_m_00_01simd4u8_01_4.html',1,'nvbio::aln::priv']]],
  ['hammingcheckpointcontext',['HammingCheckpointContext',['../structnvbio_1_1aln_1_1priv_1_1_hamming_checkpoint_context.html',1,'nvbio::aln::priv']]],
  ['hammingcheckpointedscoringcontext',['HammingCheckpointedScoringContext',['../structnvbio_1_1aln_1_1priv_1_1_hamming_checkpointed_scoring_context.html',1,'nvbio::aln::priv']]],
  ['hammingdistancealigner',['HammingDistanceAligner',['../structnvbio_1_1aln_1_1_hamming_distance_aligner.html',1,'nvbio::aln']]],
  ['hammingdistancetag',['HammingDistanceTag',['../structnvbio_1_1aln_1_1_hamming_distance_tag.html',1,'nvbio::aln']]],
  ['hammingscoringcontext',['HammingScoringContext',['../structnvbio_1_1aln_1_1priv_1_1_hamming_scoring_context.html',1,'nvbio::aln::priv']]],
  ['hammingsubmatrixcontext',['HammingSubmatrixContext',['../structnvbio_1_1aln_1_1priv_1_1_hamming_submatrix_context.html',1,'nvbio::aln::priv']]],
  ['has_5fsecond',['has_second',['../structnvbio_1_1io_1_1has__second.html',1,'nvbio::io']]],
  ['has_5fsecond_5fpaired',['has_second_paired',['../structnvbio_1_1io_1_1has__second__paired.html',1,'nvbio::io']]],
  ['has_5fsecond_5funpaired',['has_second_unpaired',['../structnvbio_1_1io_1_1has__second__unpaired.html',1,'nvbio::io']]],
  ['hash_5ffunctor1',['hash_functor1',['../structhash__functor1.html',1,'']]],
  ['hash_5ffunctor2',['hash_functor2',['../structhash__functor2.html',1,'']]],
  ['header_5fobject',['header_object',['../structnvbio_1_1html_1_1header__object.html',1,'nvbio::html']]],
  ['hfile',['hFILE',['../structh_f_i_l_e.html',1,'']]],
  ['hfile_5fbackend',['hFILE_backend',['../structh_f_i_l_e__backend.html',1,'']]],
  ['hfile_5ffd',['hFILE_fd',['../structh_f_i_l_e__fd.html',1,'']]],
  ['hfile_5fmem',['hFILE_mem',['../structh_f_i_l_e__mem.html',1,'']]],
  ['hfile_5fnet',['hFILE_net',['../structh_f_i_l_e__net.html',1,'']]],
  ['hgacc_5ft',['hgacc_t',['../structhgacc__t.html',1,'']]],
  ['hi_5fbits_5ffunctor',['hi_bits_functor',['../structnvbio_1_1hi__bits__functor.html',1,'nvbio']]],
  ['hi_5fbits_5ffunctor_3c_20uint16_2c_20uint32_20_3e',['hi_bits_functor&lt; uint16, uint32 &gt;',['../structnvbio_1_1hi__bits__functor_3_01uint16_00_01uint32_01_4.html',1,'nvbio']]],
  ['hi_5fbits_5ffunctor_3c_20uint32_2c_20uint32_20_3e',['hi_bits_functor&lt; uint32, uint32 &gt;',['../structnvbio_1_1hi__bits__functor_3_01uint32_00_01uint32_01_4.html',1,'nvbio']]],
  ['hi_5fbits_5ffunctor_3c_20uint32_2c_20uint64_20_3e',['hi_bits_functor&lt; uint32, uint64 &gt;',['../structnvbio_1_1hi__bits__functor_3_01uint32_00_01uint64_01_4.html',1,'nvbio']]],
  ['hi_5fbits_5ffunctor_3c_20uint8_2c_20uint32_20_3e',['hi_bits_functor&lt; uint8, uint32 &gt;',['../structnvbio_1_1hi__bits__functor_3_01uint8_00_01uint32_01_4.html',1,'nvbio']]],
  ['histogram',['Histogram',['../structnvbio_1_1alndiff_1_1_histogram.html',1,'nvbio::alndiff']]],
  ['histogram2d',['Histogram2d',['../structnvbio_1_1alndiff_1_1_histogram2d.html',1,'nvbio::alndiff']]],
  ['histogram2d_3c_2012_2c_2010_20_3e',['Histogram2d&lt; 12, 10 &gt;',['../structnvbio_1_1alndiff_1_1_histogram2d.html',1,'nvbio::alndiff']]],
  ['histogram2d_3c_2012_2c_2012_20_3e',['Histogram2d&lt; 12, 12 &gt;',['../structnvbio_1_1alndiff_1_1_histogram2d.html',1,'nvbio::alndiff']]],
  ['histogram2d_3c_2016_2c_2016_20_3e',['Histogram2d&lt; 16, 16 &gt;',['../structnvbio_1_1alndiff_1_1_histogram2d.html',1,'nvbio::alndiff']]],
  ['histogram2d_3c_2032_2c_2010_20_3e',['Histogram2d&lt; 32, 10 &gt;',['../structnvbio_1_1alndiff_1_1_histogram2d.html',1,'nvbio::alndiff']]],
  ['histogram2d_3c_207_2c_2012_20_3e',['Histogram2d&lt; 7, 12 &gt;',['../structnvbio_1_1alndiff_1_1_histogram2d.html',1,'nvbio::alndiff']]],
  ['histogram_3c_20256_20_3e',['Histogram&lt; 256 &gt;',['../structnvbio_1_1alndiff_1_1_histogram.html',1,'nvbio::alndiff']]],
  ['histogram_3c_208_20_3e',['Histogram&lt; 8 &gt;',['../structnvbio_1_1alndiff_1_1_histogram.html',1,'nvbio::alndiff']]],
  ['hit_5fcompare',['hit_compare',['../structnvbio_1_1bowtie2_1_1cuda_1_1hit__compare.html',1,'nvbio::bowtie2::cuda']]],
  ['hitarray',['HitArray',['../structnvbio_1_1bowtie2_1_1cuda_1_1_read_hits_index_device_view_1_1_hit_array.html',1,'nvbio::bowtie2::cuda::ReadHitsIndexDeviceView']]],
  ['hitarray',['HitArray',['../structcufmi_1_1bowtie2_1_1cuda_1_1_read_hits_index_device_view_1_1_hit_array.html',1,'cufmi::bowtie2::cuda::ReadHitsIndexDeviceView']]],
  ['hitqueues',['HitQueues',['../structnvbio_1_1bowtie2_1_1cuda_1_1_hit_queues.html',1,'nvbio::bowtie2::cuda']]],
  ['hitqueues',['HitQueues',['../structcufmi_1_1bowtie2_1_1cuda_1_1_hit_queues.html',1,'cufmi::bowtie2::cuda']]],
  ['hitqueuesdeviceview',['HitQueuesDeviceView',['../structcufmi_1_1bowtie2_1_1cuda_1_1_hit_queues_device_view.html',1,'cufmi::bowtie2::cuda']]],
  ['hitqueuesdeviceview',['HitQueuesDeviceView',['../structnvbio_1_1bowtie2_1_1cuda_1_1_hit_queues_device_view.html',1,'nvbio::bowtie2::cuda']]],
  ['hitreference',['HitReference',['../structnvbio_1_1bowtie2_1_1cuda_1_1_hit_reference.html',1,'nvbio::bowtie2::cuda']]],
  ['hitreference',['HitReference',['../structcufmi_1_1bowtie2_1_1cuda_1_1_hit_reference.html',1,'cufmi::bowtie2::cuda']]],
  ['host_5fdevice_5fbuffer',['host_device_buffer',['../structnvbio_1_1cuda_1_1host__device__buffer.html',1,'nvbio::cuda']]],
  ['host_5fdevice_5fbuffer_5fsync',['host_device_buffer_sync',['../structnvbio_1_1cuda_1_1host__device__buffer__sync.html',1,'nvbio::cuda']]],
  ['host_5fdevice_5fbuffer_5fzero_5fcopy',['host_device_buffer_zero_copy',['../structnvbio_1_1cuda_1_1host__device__buffer__zero__copy.html',1,'nvbio::cuda']]],
  ['host_5ftag',['host_tag',['../structnvbio_1_1host__tag.html',1,'nvbio']]],
  ['hostbwtconfigcpubucketer',['HostBWTConfigCPUBucketer',['../structnvbio_1_1cuda_1_1_host_b_w_t_config_c_p_u_bucketer.html',1,'nvbio::cuda']]],
  ['hostbwtconfiggpubucketer',['HostBWTConfigGPUBucketer',['../structnvbio_1_1cuda_1_1_host_b_w_t_config_g_p_u_bucketer.html',1,'nvbio::cuda']]],
  ['hostbwthandler',['HostBWTHandler',['../structnvbio_1_1_host_b_w_t_handler.html',1,'nvbio']]],
  ['hostbwthandler_3c_20packedstream_3c_20word_5ftype_20_2a_2c_20uint8_2c_20symbol_5fsize_2c_20big_5fendian_2c_20uint64_20_3e_20_3e',['HostBWTHandler&lt; PackedStream&lt; word_type *, uint8, SYMBOL_SIZE, BIG_ENDIAN, uint64 &gt; &gt;',['../structnvbio_1_1_host_b_w_t_handler_3_01_packed_stream_3_01word__type_01_5_00_01uint8_00_01_s_y_mece7f5f021aa7d905197083a5b114cf2.html',1,'nvbio']]],
  ['hostcigararray',['HostCigarArray',['../structnvbio_1_1io_1_1_host_cigar_array.html',1,'nvbio::io']]],
  ['hostcoresetsuffixbucketer',['HostCoreSetSuffixBucketer',['../structnvbio_1_1priv_1_1_host_core_set_suffix_bucketer.html',1,'nvbio::priv']]],
  ['hostoutputbatchpe',['HostOutputBatchPE',['../structnvbio_1_1io_1_1_host_output_batch_p_e.html',1,'nvbio::io']]],
  ['hostoutputbatchse',['HostOutputBatchSE',['../structnvbio_1_1io_1_1_host_output_batch_s_e.html',1,'nvbio::io']]],
  ['hostsetsuffixbucketer',['HostSetSuffixBucketer',['../structnvbio_1_1priv_1_1_host_set_suffix_bucketer.html',1,'nvbio::priv']]],
  ['hoststringsetradices',['HostStringSetRadices',['../structnvbio_1_1priv_1_1_host_string_set_radices.html',1,'nvbio::priv']]],
  ['hostthreadscheduler',['HostThreadScheduler',['../structnvbio_1_1aln_1_1_host_thread_scheduler.html',1,'nvbio::aln']]],
  ['hostvectorarray',['HostVectorArray',['../structnvbio_1_1_host_vector_array.html',1,'nvbio']]],
  ['hostvectorarray_3c_20io_3a_3anvbio_3a_3aio_3a_3acigar_20_3e',['HostVectorArray&lt; io::nvbio::io::Cigar &gt;',['../structnvbio_1_1_host_vector_array.html',1,'nvbio']]],
  ['hostvectorarray_3c_20nvbio_3a_3amemrange_20_3e',['HostVectorArray&lt; nvbio::MEMRange &gt;',['../structnvbio_1_1_host_vector_array.html',1,'nvbio']]],
  ['hostvectorarray_3c_20uint8_20_3e',['HostVectorArray&lt; uint8 &gt;',['../structnvbio_1_1_host_vector_array.html',1,'nvbio']]],
  ['html_5fobject',['html_object',['../structnvbio_1_1html_1_1html__object.html',1,'nvbio::html']]],
  ['hts_5fcram_5fidx_5ft',['hts_cram_idx_t',['../structhts__cram__idx__t.html',1,'']]],
  ['hts_5fitr_5ft',['hts_itr_t',['../structhts__itr__t.html',1,'']]],
  ['hts_5fpair64_5ft',['hts_pair64_t',['../structhts__pair64__t.html',1,'']]],
  ['htsbamreader',['HTSBAMReader',['../struct_h_t_s_b_a_m_reader.html',1,'']]],
  ['htsbamwriter',['HTSBAMWriter',['../struct_h_t_s_b_a_m_writer.html',1,'']]],
  ['htsfile',['htsFile',['../structhts_file.html',1,'']]]
];
